### ISSUE TITLE
Check for ordering of plugins

### ISSUE THREAD

**Issue by davecramer** [awslabs/aws-advanced-jdbc-wrapper#177]
There are comments in the docs that suggest that there is a preferred order of plugins. Do we check this when we load the plugins ?

**Comment by davecramer** [comment]
@karenc-bq why are we telling people there is a preferred order then ? 
I'd question just how much overhead there might be. There might be 10 plugins at most.

**Comment by karenc-bq** [comment]
@davecramer https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/using-plugins/UsingTheHostMonitoringPlugin.md#:~:text=Note%3A%20When,failover%2C...%2Cefm Is this the documentation you are pointing to saying that we are telling people there is a preferred plugin order?

**Comment by hsuamz** [comment]
Closing this issue, since https://github.com/awslabs/aws-advanced-jdbc-wrapper/pull/332 has been added which includes our recommended default plugins out of the box.
