### ISSUE TITLE
Set wrapperPlugins without writing code

### ISSUE THREAD

**Issue by visit1985** [awslabs/aws-advanced-jdbc-wrapper#218]
The latest announcement advertises this driver as drop-in compatible. I understand that I have to add the jar to my project and change the protocol prefix to `jdbc:aws-wrapper:` in the JDBC connection URL. But how do I set `wrapperPlugins` without changing my code? The docs do not suggest any method for that. Can I add the connection plugin manager parameters as URL parameters to the JDBC connection URL?

**Comment by sergiyvamz** [comment]
Hello @visit1985 

Thank you for reaching out! `wrapperPlugins` parameter could be specified by one of the following way.

1) You can change code of your application. 

```
Properties properties = new Properties();
properties.setProperty("wrapperPlugins", "failover,efm");
Connection connection = DriverManager.getConnection("jdbc:aws-wrapper:postgresql://....", properties);
```

2) You can add `wrapperPlugins` parameter to connection string.

```
Connection connection = DriverManager.getConnection(
     "jdbc:aws-wrapper:postgresql://....?wrapperPlugins=failover,efm", "user", "password"); 
```

I hope that answers your question.

**Comment by maximevdk-tidal** [comment]
Maybe this could be written somewhere more obvious in the documentation on the plugins.
