### ISSUE TITLE
Option for reader failover to respect the topology 

### ISSUE THREAD

**Issue by Sovietaced** [awslabs/aws-advanced-jdbc-wrapper#223]
### Describe the feature

This morning I ran into a production issue that I believe was related to this library and the failover plugin specifically. We have an RDS Aurora cluster with a reader and writer node. We typically use the reader node to offload read-only traffic from the writer node (ie. to support UI workflows). As such, our reader node is 2-4 times the size of a writer node. 

We ran into a situation where our reader node got overwhelmed and temporarily refused DB connections. This situation caused the failover plugin to attempt a reader failover and since the reader node was refusing DB connections the writer node won the connection race. Unfortunately the overwhelming read load ended up spilling over to the writer node, where it overloaded the writer node, and finally broke critical workloads.

Prior to using this JDBC driver we would rely on the RDS Aurora cluster endpoints, which would remain consistent with the underlying database topology and didn't change when a DB instance was under heavy load.
I understand that this behavior is[ documented](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/wrapper/src/main/java/software/amazon/jdbc/plugin/failover/ClusterAwareReaderFailoverHandler.java#L113-L133) and frankly I see a use case for having read traffic failover to the writer node. 

Having said that I think it would be useful to have an option for reader failover to respect the topology in a similar manner to how writer failover works. In this mode read-only connections would only be made to the writer node if and only if it was the only remaining host in the topology. 

For our team we specifically write our applications to leverage read replicas because we don't want to overwhelm the writer node since it is a finite resource (relative to readers) that can only scale vertically. 

### Use Case

We use read replicas to offload traffic from our writer node. It is not acceptable for us to send overflow read traffic to our writer nodes. We would like to pin read traffic to reader nodes as long as they exist in the topology. 

### Proposed Solution

I suggest adding a feature flag to the failover plugin like `strictFailover` or `strictReaderFailover` which ensures that reader failover respects the topology and only fails over to a writer node if it is the last resort. 

### Other Information

Happy to submit a PR. 

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### The AWS Advanced JDBC Driver version used

1.0.0

### JDK version used

JDK 11

### Operating System and version

Ubuntu

**Comment by davecramer** [comment]
@Sovietaced Thanks for this report. 
In principle I agree with this, however since the reader is now not accepting connections we consider it to have failed and fail over as you pointed out. Once that happens then from the driver's point of view there is only one option left which is the writer. I think the challenge will be figuring out that the reader really hasn't failed it is just temporarily available. That said assuming we can figure this out how do you want the driver to behave with the failed connection? Just not connect ?

Dave

**Comment by Sovietaced** [comment]
> I think the challenge will be figuring out that the reader really hasn't failed it is just temporarily available.

I was hoping we could reference the topology for this. However when the driver is configured for read-only I'm not sure if the driver will exercise writer nodes for topology discovery. Another thing that I don't know is how the aurora proprietary SQL tables are populated. If they are populated by some out of band control plane I would expect the topology to be consistent with what we see on the AWS console during this time. 

> That said assuming we can figure this out how do you want the driver to behave with the failed connection?

I would like the reader failover to behave similar to the writer failover. The writer failover does [two things concurrently](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/ab70730743512ed921bbcdfcab7f5624f5c8b278/wrapper/src/main/java/software/amazon/jdbc/plugin/failover/ClusterAwareWriterFailoverHandler.java#L146-L156) I believe:
1. Attempts to reconnect to the writer
2. Performs topology discovery on the reader node to look for a new writer

So for the reader failover I could see the following behavior being helpful:
1. Attempt to connect to any reader node (as long as the topology claims there are reader nodes). If the topology claims there are no reader nodes, connect to the writer node. 
2. Perform topology discovery on any other available node to get the most up to date topology information

**Comment by davecramer** [comment]
> So for the reader failover I could see the following behavior being helpful:
> 
> 1. Attempt to connect to any reader node (as long as the topology claims there are reader nodes). If the topology claims there are no reader nodes, connect to the writer node.
> 2. Perform topology discovery on any other available node to get the most up to date topology information

Right so if I understand you correctly as long as there is a reader node in the topology the driver should just continue to attempt to connect to the reader node if it was connected there in the first place?

**Comment by Sovietaced** [comment]
> Right so if I understand you correctly as long as there is a reader node in the topology the driver should just continue to attempt to connect to the reader node if it was connected there in the first place?

It could attempt to connect to the original reader node it was connected or any other reader node. I haven't thought too deeply about the implications of connect to any other reader node, could be a bad idea.

**Comment by sergiyvamz** [comment]
Hello @Sovietaced 

A fix has been implemented. Will you be able to test out a snapshot build and let us know if the issue persists?
https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/UsingTheJdbcDriver.md#using-a-snapshot-of-the-driver

Thank you!

**Comment by Sovietaced** [comment]
> Hello @Sovietaced
> 
> A fix has been implemented. Will you be able to test out a snapshot build and let us know if the issue persists?

Hey @sergiyvamz, unfortunately I don't think I'll be able to test this out in a production-like workload since our company announced it was shutting down today. I took a look at the diff and it looks fine. When I implemented this in my own fork I simply changed the `getHostsByPriority` method but yours looks more robust so it should work.

**Comment by Sovietaced** [comment]
Anyhow, I ported over my unit test: https://github.com/awslabs/aws-advanced-jdbc-wrapper/pull/247
