### ISSUE TITLE
Ability to use IAM over Jump Boxes

### ISSUE THREAD

**Issue by frugecn** [awslabs/aws-advanced-jdbc-wrapper#236]
### Describe the feature

Be able to use the iam plugin when going through a jump box.  Currently, it errors saying that localhost does not match the rds endpoint structure.

### Use Case

I'm trying to use JDBC to test applications locally connecting to Aurora Database through JDBC where it is required to use a jump box.  With the jump box configuration, you have to use the localhost address when connecting to the database.

### Proposed Solution

Add a field to the wrapper that would be the endpoint of the database instance (failover??) that when localhost is used the endpoint field could be used in its place.

### Other Information

Unsupported AWS hostname localhost. Amazon domain name in format *.AWS-Region.rds.amazonaws.com or *.rds.AWS-Region.amazonaws.com.cn is expected.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### The AWS Advanced JDBC Driver version used

1.0.0

### JDK version used

OpenJDK 18.0.02

### Operating System and version

Windows 11

**Comment by karenc-bq** [comment]
Hi @frugecn, thank you for reaching out.

When you are using a jump box, you can specify the AWS domain name through the connection parameter provided by the Failover Connection Plugin: `clusterInstanceHostPattern`.

Here is a sample connection string: `jdbc:aws-wrapper:postgresql://localhost:5432/db?wrapperPlugins=iam,failover&clusterInstanceHostPattern=?.hash-number.us-east-2.rds.amazonaws.com`

You can learn more about `clusterInstanceHostPattern` [here](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/using-plugins/UsingTheFailoverPlugin.md#host-pattern).

**Comment by frugecn** [comment]
Tried this connection string:

`jdbc:aws-wrapper:postgresql://localhost:5432/mypgdb?wrapperPlugins=iam,failover&clusterInstanceHostPattern=?.cluster-cpjzfiwcidkb.us-east-1.rds.amazonaws.com`

but get this result:

Unsupported AWS hostname localhost. Amazon domain name in format *.AWS-Region.rds.amazonaws.com or *.rds.AWS-Region.amazonaws.com.cn is expected.

I'm not quite understanding the documentation.  It refers to customHost in two spots, but in the case of localhost, how would it know to use the correct endpoint during the IAM authentication?  

Based off of this part of the article:

`Since there isn't enough information from the custom domain alone to create the instance endpoints, you should set the clusterInstanceHostPattern to ?.customHost, making the connection string jdbc:aws-wrapper:postgresql://customHost:1234/test?clusterInstanceHostPattern=?.customHost. `

I would think that the connection string should have `?.localhost` as the value for the clusterInstanceHostPattern, which wouldn't match the pattern needed.

**Comment by frugecn** [comment]
Something similar to this where it tunnels to a bastion and then connects to the rds endpoint.

`ssh -i mypemfile.pem -L 5432:rdsendpoint:5432 -t ec2username@ec2-dns-address`

**Comment by karenc-bq** [comment]
You are correct, if your setting maps `localhost` directly to the RDS endpoint, then your `clusterInstanceHostPattern` should be `?.localhost`.

The IAM authentication plugin currently does not support generating IAM token with a custom endpoint. We are adding an `iamHost` parameter in #240 to support this workflow.

Once this PR has been merged you would be able to connect via
```
jdbc:aws-wrapper:postgresql://localhost:5432/mypgdb?wrapperPlugins=iam,failover&clusterInstanceHostPattern=?.localhost&iamHost=rdsendpoint`
```

Thank you for your patience.

**Comment by karenc-bq** [comment]
Hi @frugecn, the PR has been merged, would you be able to test out the [snapshot build](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/UsingTheJdbcDriver.md#using-a-snapshot-of-the-driver) and let us know if the issue persists? Thank you.

**Comment by frugecn** [comment]
I'm getting an java.io.EOFException, but I'm thinking it may be on my side.  At least we're past the localhost error to begin with.  Thanks for looking into it.

**Comment by frugecn** [comment]
It was an error on my side.  It is working with your change.

**Comment by karenc-bq** [comment]
Thank you, I will close this issue for now. Please feel free to reach out again if new issues show up.
