### ISSUE TITLE
Custom AwsCredentialsProvider

### ISSUE THREAD

**Issue by dlesl** [awslabs/aws-advanced-jdbc-wrapper#275]
### Describe the feature

The IAM authentication plugin currently uses the [DefaultCredentialsProvider](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/97dc84fe159245c328afb8444df1032a0fe707d2/wrapper/src/main/java/software/amazon/jdbc/plugin/IamAuthConnectionPlugin.java#L155). It would be great if there were a way to customise this.

### Use Case

This would be useful in cases where we need to use a role assumed through STS to do the IAM auth.

### Proposed Solution

The connection string could take a parameter specifying the name of a user-defined factory class to use to provide the `AwsCredentialsProvider`. There might also need to be a mechanism to pass some configuration to that factory class, eg. through a second parameter.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### The AWS Advanced JDBC Driver version used

1.0.0

### JDK version used

N/A

### Operating System and version

N/A

**Comment by hsuamz** [comment]
Thank you for sharing some feedback regarding the driver.

We will discuss the feature with the team. If we need anything clarified, we'll reach out here.

Thanks again,

Matthew

**Comment by congoamz** [comment]
Hi @dlesl,

We have created a PR for this feature request, could you please take a look at the documentation/example found [here](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/da82e99f57f09b1ba65de30883a2d15fe77d9411/docs/using-the-jdbc-driver/custom-configuration/AwsCredentialsConfiguration.md) and let us know if this meets your needs/expectations? The rest of the PR is [here](https://github.com/awslabs/aws-advanced-jdbc-wrapper/pull/306). Let me know if you have any questions, thanks!

**Comment by dlesl** [comment]
Thanks for implementing the feature @congoamz. It looks like this would do the trick! My only concern is around connecting to multiple databases which require different credentials. Would it be possible to add a way for the lambda passed to `AwsCredentialsManager.setCustomHandler` to distinguish between databases? For example by taking a `Function<String, AwsCredentialsProvider>` which takes the connection string, or something similar with the parsed connection string?

**Comment by congoamz** [comment]
@dlesl thanks for taking a look. To clarify, is the case you are concerned about the need to connect to multiple databases with different **AWS** credentials or with different **database** credentials?

**Comment by dlesl** [comment]
Different AWS credentials. For example, imagine that you need to connect to databases in two different AWS accounts, so you would like to use a separate `StsAssumeRoleCredentialsProvider` for each database.

**Comment by congoamz** [comment]
@dlesl thanks for the suggested tweak, I've changed the lambda so that a `HostSpec` and `Properties` object are passed to the lambda, which reflect the requested connection info. For example, the connection URL can be pulled out of the HostSpec. Can you take a look at the revised PR, specifically the example, and get back to me with any feedback?

**Comment by congoamz** [comment]
Awesome, thanks! I'll close this issue now as I just merged it in
