### ISSUE TITLE
Runtime Exception: No wrapper class exists for 'org.postgresql.jdbc.PgArray'. when calling resultSet.getObject

### ISSUE THREAD

**Issue by jaybocc2** [awslabs/aws-advanced-jdbc-wrapper#284]
We are looking at using the aws jdbc wrapper w/ aurora postgres to improve our database failovers but during some testing we are encountering some runtime exceptions w/ wrapper classes when we call `getObject` on a query results

ex:
```
Caused by: java.lang.RuntimeException: No wrapper class exists for 'org.postgresql.jdbc.PgArray'.
	at software.amazon.jdbc.util.WrapperUtils.wrapWithProxyIfNeeded(WrapperUtils.java:268)
	at software.amazon.jdbc.util.WrapperUtils.executeWithPlugins(WrapperUtils.java:228)
	at software.amazon.jdbc.wrapper.ResultSetWrapper.getObject(ResultSetWrapper.java:708)
...Truncated irrelevant stack
```

**Comment by hsuamz** [comment]
Hello @jaybocc2,

Thanks for reaching out. Could we get a few details regarding your environment?

- What version of the PGJDBC driver are you using with the AWS JDBC Wrapper?
- Are you able to share a code snippet that is causing this error?

Thanks,

Matthew

**Comment by jaybocc2** [comment]
@hsuamz we are using version 1.0.0 of the aws-wrapper and we are using 42.5.1 of the postgresql driver


a pseudo example
```
final Statement sS = conn.createStatement()
final ResultSet resultSet = sS.executeQuery("SELECT colname FROM tablename ORDER BY pkcolname");
final ResultSetMetaData metaData = resultSet.getMetaData();
final int colCount = metaData.getColumCount();
for (int i = 1; i <= colCount; i++) {
  final Object val = resultSet.getObject(i)
}
```

**Comment by karenc-bq** [comment]
Hi @jaybocc2, thank you for raising this issue and providing the code snippet. We are working on a fix in PR #285.
Thank you for your patience!

**Comment by jaybocc2** [comment]
Thanks for fixing! 
@karenc-bq and @hsuamz do you know when there will be another release or should we compile ourselves for the time being?

**Comment by hsuamz** [comment]
Hello @jaybocc2,

Are you currently evaluating the driver for production use or do you have a timeline where you'd want an official release? There are issues that we'd like to include in the next release and we are determining scheduling.

For convenience, we do offer nightly builds here: https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/UsingTheJdbcDriver.md#using-a-snapshot-of-the-driver and this build would contain the fix you see here, alongside other fixes.

Thanks,

Matthew

**Comment by jaybocc2** [comment]
We are currently testing, however if there are important fixes we can probably easily wait until the new year before really pushing for prod rollout.

**Comment by karenc-bq** [comment]
Hi @jaybocc2, we've released a new version of the driver that resolves this issue. Please download the latest 1.0.1 version of the driver. We'll be closing this ticket. Thank you.
