### ISSUE TITLE
ReadWriteSplittingPlugin is not available in release version 1.0.0 and Not able to build the aws-advanced-jdbc-wrapper in local

### ISSUE THREAD

**Issue by nalininagarathinam** [awslabs/aws-advanced-jdbc-wrapper#287]
Hi Team, 

There are two issues/queries with [aws-advanced-jdbc-wrapper](https://github.com/awslabs/aws-advanced-jdbc-wrapper).

1. As per the documentation, tried to use the ReadWriteSplittingPlugin for our project. But it looks like ReadWriteSplittingPlugin feature is yet to be released as it is not available as part of version 1.0.0.

https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/using-plugins/UsingTheReadWriteSplittingPlugin.md

Could you please advise when this plugin will be available?

2. Hence, tried to clone the repository in the local system and build the project by running the command "./gradlew build".
But It's generating the jar only with manifest file.  Couldn't able to build in local system. Please advise on this.

Attached for your reference. 

[aws-advanced-jdbc-wrapper-1.0.0.jar.zip](https://github.com/awslabs/aws-advanced-jdbc-wrapper/files/10212952/aws-advanced-jdbc-wrapper-1.0.0.jar.zip)

**Comment by hsuamz** [comment]
Thanks for reaching out @nalininagarathinam. Answers to your questions down below:

1. That's right. The ongoing work with read / write splitting has not been officially released. Release notes specific to our released version can be found with the corresponding tag: https://github.com/awslabs/aws-advanced-jdbc-wrapper/releases/tag/1.0.0. As we complete on read / write splitting, we can share more details here on when to expect a public release.

2. For convenience, we have snapshot builds configured for the repo. For reference: https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/development-guide/DevelopmentGuide.md. If you're wanting to build locally, we'll take a look at your reference and get back to you.

Thanks.

**Comment by hsuamz** [comment]
Hello @nalininagarathinam,

We released a new version of the driver, 1.0.1, which includes Read / Write Splitting as an experimental feature. There is on-going work to streamline some of the behaviour to match what is expected from MySQL. However, functionality is there if you wanted to give it a go.

If there's any feedback to share, we would also be very much interested in hearing it.

Thanks,

Matthew

**Comment by nalininagarathinam** [comment]
Thanks Matthew, Can we use it in production if we want to give it a go?

**Comment by hsuamz** [comment]
We currently do no recommend the usage of Read / Write Splitting in a production environment given the on-going changes. It is released as experimental to try out in a development environment. However, the driver itself contains many improvements and we encourage people to upgrade with the note of having Read / Write Splitting disabled in a production environment.

For visibility, in addition to some on-going changes, we're also conducting performance analysis and will publish that on our README.md once ready to share. Likewise, we will also update you here once the feature is ready for production use.

Thanks,

Matthew

**Comment by hsuamz** [comment]
@nalininagarathinam, we have recently released v2 of the driver that includes the read / write splitting plugin. Please feel free to download the latest version of the driver: https://github.com/awslabs/aws-advanced-jdbc-wrapper/releases/tag/2.1.1.

We'll be closing this issue, but please feel free to share any feedback and continue discussion through our GitHub.
