### ISSUE TITLE
Accept URLs without wrapper prefix in the scheme

### ISSUE THREAD

**Issue by peay** [awslabs/aws-advanced-jdbc-wrapper#320]
### Describe the feature

Today, the driver class only accepts URLs that start with `jdbc:aws-wrapper:`. I've hit some cases where this is a limitation. Could the class also accept "un-wrapped" schemes like `jdbc:postgresql://`?

### Use Case

When using Apache Spark to read/write with JDBC, there are per-database dialects to map the database types from and to internal data types. For PostgreSQL, [the dialect enables only when 
URL starts with `jdbc:postgresql://`](https://github.com/apache/spark/blob/v3.2.0/sql/core/src/main/scala/org/apache/spark/sql/jdbc/PostgresDialect.scala#L29). Hence, it is not currently possible to use `jdbc:aws-wrapper:postgresql` with the Apache Spark and JDBC.

However, Apache Spark supports setting the driver class name explicitly: i.e., we can pass `software.amazon.jdbc.Driver`. If this driver class accepted regular URLs, it would thus be possible to use the JDBC source/sink with a `postgresql://` URL and the AWS JDBC wrapper.

### Proposed Solution

- Accepting `jdbc:postgresql://` or similar in `software.amazon.jdbc.Driver` would be a good first step.
- Overall, it'd be useful to be able to use the wrapper with the standard schemes - i.e., have some way to have the wrapper register itself at `jdbc:postgresql://` directly. This would also help with integration in other systems.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### The AWS Advanced JDBC Driver version used

1.0.0

### JDK version used

1.11

### Operating System and version

Amazon Linux 2

**Comment by davecramer** [comment]
Can you explain your use case? The driver proxies an underlying driver so it eventually loads the postgres driver. I'm unsure what you would do with the postgres driver being loaded initially?

**Comment by davecramer** [comment]
Unfortunately we cannot accept `jdbc:postgresql` this conflicts with the PostgreSQL driver. I'm afraid you will have to get the Spark folks to fix this.

**Comment by peay** [comment]
OK, that's certainly fair. I think overall beyond Spark, there's a bunch of other systems where it would be useful to be able to, say, use a specific JAR `aws-advanced-jdbc-wrapper-dropin.jar` that would act as a drop-in replacement for supported schemes (e.g., by de-registering such drivers if present, and registering the wrapper instead), when it is the intended behavior. This would greatly simplify adoption -- however, I can understand that this can make things a bit messy.

**Comment by davecramer** [comment]
Interesting idea. Not sure how to deal with this. Certainly this is not for the average user. How does spark determine which dialect to use ? We could mimic other drivers that way.

**Comment by peay** [comment]
Spark only checks the [URL scheme today to select the dialect](https://github.com/apache/spark/blob/v3.2.0/sql/core/src/main/scala/org/apache/spark/sql/jdbc/PostgresDialect.scala#L29) today.

**Comment by davecramer** [comment]
Seems like a failing on their part. Hibernate allows you to specify a dialect
