### ISSUE TITLE
Password change not picked up

### ISSUE THREAD

**Issue by NikolayMetchev** [awslabs/aws-advanced-jdbc-wrapper#336]
### Describe the bug

When are using the wrapper in conjunction with Hikari and you change the username and password the Wrapper seems to be caching credentials and not changing them.
In our application we have rotating credentials and this causes a failure.
This is a regression in 1.0.1 from 1.0.0

### Expected Behavior

changing the username and password in hikari should update the AWS wrapper credentials

### What plugins are used? What other connection properties were set?

none

### Current Behavior

Hikari connections keep using old credentails

### Reproduction Steps

I have attached a gradle project with a unit test which fails with version 1.0.1 and passes with version 1.0.0
To run the test simply run 
`./gradlew test`
[bug.tar.gz](https://github.com/awslabs/aws-advanced-jdbc-wrapper/files/10673979/bug.tar.gz)

### The AWS Advanced JDBC Driver version used

1.0.1

### JDK version used

17.0.4

### Operating System and version

MacOS Ventura and Linux

**Comment by karenc-bq** [comment]
Hi @NikolayMetchev, thank you for raising this issue. We will investigate this and keep you updated with our progress.

**Comment by karenc-bq** [comment]
Hi @NikolayMetchev, can you please

**Comment by NikolayMetchev** [comment]
@karenc-bq I can confirm that with version aws-advanced-jdbc-wrapper-1.0.2-20230217.222530-20.jar the bug has been fixed.

**Comment by hsuamz** [comment]
Thanks for confirming @NikolayMetchev, we'll be closing this issue.

**Comment by NikolayMetchev** [comment]
When can I expect the next release?

**Comment by hsuamz** [comment]
@NikolayMetchev, please expect a maintenance release in the coming week. For visibility, we'll be sharing information on a regular release cadence soon.
