### ISSUE TITLE
test: Should add a test to make sure this link exists

### ISSUE THREAD

**Issue by davecramer** [awslabs/aws-advanced-jdbc-wrapper#344]
https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/d11a866e4616e24e90703ffff32b065f5e083b97/wrapper/src/main/resources/messages.properties#L37

**Comment by davecramer** [comment]
Same with this https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/d11a866e4616e24e90703ffff32b065f5e083b97/wrapper/src/main/resources/messages.properties#L138

However I'd argue that it is a duplicate and should be removed

**Comment by joyc-bq** [comment]
Hi @davecramer, this test is now in review [PR #351](https://github.com/awslabs/aws-advanced-jdbc-wrapper/pull/351)

**Comment by joyc-bq** [comment]
This test was approved and merged, issue is now closed
