### ISSUE TITLE
Provide option to bypass ResultSetWrapper

### ISSUE THREAD

**Issue by thomas4019** [awslabs/aws-advanced-jdbc-wrapper#366]
### Describe the feature

I'd like an method to return the underlying ResultSet which can be used to directly access the returned rows. This could be used in cases where a bunch of fields are being read and the overhead from all the wrapping isn't needed.

### Use Case

Based on some performance testing, using this jdbc wrapper around our postgres caused our CPU usage to increase by about 100%. The majority of the costs seem to come from the calls to `ResultSet.getLong`, `ResultSet.getBoolean`, etc since we call these many times for each record returned and some queries return thousands of rows.

### Proposed Solution

I'd like an method to return the underlying ResultSet e.g.
```
public ResultSet getRawResultSet() {
  return this.resultSet;
}
```

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### The AWS Advanced JDBC Driver version used

1.0.1

### JDK version used

17.0.6

### Operating System and version

Linux x64 on AWS

**Comment by aaronchung-bitquill** [comment]
Hi @thomas4019 

Thank you for reaching out. 

I believe the `ResultSetWrapper.unwrap()` method should do what you need in getting the raw ResultSet. 

Please let us know if this works for you or if you have any other issues.

Thank you

**Comment by aaronchung-bitquill** [comment]
By the way, here is just a quick example how the `unwrap()` method can be used. 

`
    try (Connection conn = DriverManager.getConnection(CONNECTION_STRING, properties);
        Statement statement = conn.createStatement();
        ResultSet result = statement.executeQuery("SELECT * from employee")) {
      System.out.println(result.getClass().getName());
      System.out.println(result.unwrap(ResultSet.class).getClass().getName());
    }
`

**Comment by aaronchung-bitquill** [comment]
Hi @thomas4019 

I wanted to check in again to see if this solution is working for you? 

If there are no further updates on this ticket in the next 3 days, we will closing this ticket. But worry not. If you require any assistance or if this solution does not work for you, you can reopen this issue, or create a new one. 

Thank you
