### ISSUE TITLE
Mysterious Hibernate dialect class `s.a.u.AuroraPostgreSQLDialect`

### ISSUE THREAD

**Issue by dalbani** [awslabs/aws-advanced-jdbc-wrapper#367]
In https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/examples/HibernateExample/src/main/resources/META-INF/persistence.xml which accompanies the Hibernate example, there's a reference to this class:
```xml
        <property name="hibernate.dialect" value="software.amazon.utility.AuroraPostgreSQLDialect"/>
```
Unless I've missed it somewhere, this class doesn't seem present in the codebase.
Could you clarify what it's supposed to do, or if it's actually necessary after all?

**Comment by karenc-bq** [comment]
Hi @dalbani, thank you for reaching out, this file is not in the source code, it only exists in the examples directory at the moment: https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/examples/HibernateExample/src/main/java/software/amazon/utility/AuroraPostgreSQLDialect.java

**Comment by dalbani** [comment]
Doh, for some reason, I completely missed that the file was actually present in the repository! 🤷‍♂️
I'm curious though why it's not shipped in the library as a "reference" dialect implementation.
What would happen if I sticked to the regular `PostgreSQLDialect` in my app?

**Comment by dalbani** [comment]
Thanks a lot for this very clear and prompt response 👍

**Comment by karenc-bq** [comment]
We have updated the sample code and we will be closing this issue now. Thank you again @dalbani for raising this issue.

**Comment by dalbani** [comment]
Very nice 👍
