### ISSUE TITLE
MySQL Aurora failover ends up on reader instead of writer

### ISSUE THREAD

**Issue by arosso** [awslabs/aws-advanced-jdbc-wrapper#386]
### Describe the bug

We are seeing our connections to RDS MySQL Aurora 'failover' incorrectly to the reader node rather than the writer node when using the following configuration:

* JDBC Wrapper 1.0.2
* MySQL Connector 8.0.32
* Hikari 5.0.1
* A Custom Domain CNAME to the cluster writer (TTL = 1s)
* A jdbc url like this: jdbc:aws-wrapper:mysql://[custom-domain]:3306/db?clusterInstanceHostPattern=?.[clusterid].us-east-1.rds.amazonaws.com&wrapperLoggerLevel=ALL

Our test is similar to the one described in: https://github.com/awslabs/aws-mysql-jdbc/issues/377

We simply have a loop periodically getting the 1 and only connection from the connection pool, doing some transactions, releasing the connection. We then initiate a failover from the writer to a reader. We see this issue when the connection is idle in the pool and subsequently checked out. We then get this sort of error:

java.sql.SQLException: The MySQL server is running with the --read-only option so it cannot execute this statement

Attached is the anonymized debug log during the cut over.

When using the cluster writer endpoint directly the issue does not seem to happen.

### Expected Behavior

The failover should end up on the writer node.

### What plugins are used? What other connection properties were set?

Default plugins are used. No additional properties other than in the JDBC url.

### Current Behavior

The connection ends up on the reader instead of the writer.

### Reproduction Steps

See description. Attached is the debug log.
[wrapper.txt](https://github.com/awslabs/aws-advanced-jdbc-wrapper/files/11128169/wrapper.txt)

### The AWS Advanced JDBC Driver version used

1.0.2

### JDK version used

Corretto 11.0.17.8.1

### Operating System and version

Amazon Linux 2 (4.14.296-222.539.amzn2.x86_64)

**Comment by karenc-bq** [comment]
Hi @arosso, we have merged PR #390 addressing this issue. Could you please checkout our [snapshot build](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/UsingTheJdbcDriver.md#using-a-snapshot-of-the-driver) and let us know if the issue persists? Thank you.

**Comment by crystall-bitquill** [comment]
Hi @arosso,

I wanted to check in to see if the issue was resolved with the snapshot build, and to let you know that the fix is now also available on the [latest version](https://search.maven.org/artifact/software.amazon.jdbc/aws-advanced-jdbc-wrapper/2.0.0/jar?eh=) of the AWS Advanced JDBC Driver.

If there are no more updates on this ticket in the next few days, it will be closed. However, if you have any further questions or comments please feel free to create a new issue or to reopen this one.

Thank you!
