### ISSUE TITLE
Internal connection pooling does not work with Read-Write Splitting Plugin when cluster url is used

### ISSUE THREAD

**Issue by firebike** [awslabs/aws-advanced-jdbc-wrapper#467]
### Describe the bug

Internal connection pooling does not work with Read-Write Splitting Plugin when cluster url is used.

### Expected Behavior

* Perform internal connection pooling also when aurora cluster url is used in the jdbc url.
* Cluster topology is discovered by the driver and connections are opened to the available reader and writer instances.
* Read and write connection are kept in dedicated connection pools

### What plugins are used? What other connection properties were set?

readWriteSplitting

### Current Behavior

Application startup logs when cluster url is used

Redacted url: `jdbc:aws-wrapper:postgresql://us-dev-pg-cluster.cluster-xxxxxxxxxx.us-east-1.rds.amazonaws.com/xxxxxxx`

```
15:47:41.386 [main] INFO  o.h.validator.internal.util.Version - HV000001: Hibernate Validator 6.1.7.Final - {} 
15:47:41.798 [main] INFO  o.h.jpa.internal.util.LogHelper - HHH000204: Processing PersistenceUnitInfo [name: default] - {} 
15:47:41.854 [main] INFO  org.hibernate.Version - HHH000412: Hibernate ORM core version 5.4.33 - {} 
15:47:42.009 [main] INFO  o.h.annotations.common.Version - HCANN000001: Hibernate Commons Annotations {5.1.2.Final} - {} 
15:47:44.556 [main] INFO  org.hibernate.dialect.Dialect - HHH000400: Using dialect: infra.db.boundary.CustomPostgresqlDialect - {} 
15:47:46.687 [main] WARN  org.hibernate.cfg.AnnotationBinder - HHH000491: The [createdBy] association in the [features.commerceorders.entity.Status] entity uses both @NotFound(action = NotFoundAction.IGNORE) and FetchType.LAZY. The NotFoundAction.IGNORE @ManyToOne and @OneToOne associations are always fetched eagerly. - {} 
15:47:48.782 [main] INFO  o.h.e.t.j.p.i.JtaPlatformInitiator - HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform] - {} 
15:47:48.786 [main] INFO  o.s.o.j.LocalContainerEntityManagerFactoryBean - Initialized JPA EntityManagerFactory for persistence unit 'default' - {} 
```

Application startup logs when instance url is used

Redacted url: `jdbc:aws-wrapper:postgresql://backenddevusstoragestack-databas-auroradbinstance1-jjaw8nsn0cul.xxxxxxxxxx.us-east-1.rds.amazonaws.com/xxxxxxxx`

```
15:50:45.312 [main] INFO  o.h.validator.internal.util.Version - HV000001: Hibernate Validator 6.1.7.Final - {} 
15:50:45.716 [main] INFO  o.h.jpa.internal.util.LogHelper - HHH000204: Processing PersistenceUnitInfo [name: default] - {} 
15:50:45.758 [main] INFO  org.hibernate.Version - HHH000412: Hibernate ORM core version 5.4.33 - {} 
15:50:45.878 [main] INFO  o.h.annotations.common.Version - HCANN000001: Hibernate Commons Annotations {5.1.2.Final} - {} 
15:50:46.100 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting... - {} 
15:50:47.938 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed. - {} 
15:50:48.768 [main] INFO  org.hibernate.dialect.Dialect - HHH000400: Using dialect: infra.db.boundary.CustomPostgresqlDialect - {} 
15:50:51.060 [main] WARN  org.hibernate.cfg.AnnotationBinder - HHH000491: The [createdBy] association in the [features.commerceorders.entity.Status] entity uses both @NotFound(action = NotFoundAction.IGNORE) and FetchType.LAZY. The NotFoundAction.IGNORE @ManyToOne and @OneToOne associations are always fetched eagerly. - {} 
15:50:53.565 [main] INFO  o.h.e.t.j.p.i.JtaPlatformInitiator - HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform] - {} 
15:50:53.573 [main] INFO  o.s.o.j.LocalContainerEntityManagerFactoryBean - Initialized JPA EntityManagerFactory for persistence unit 'default' - {} 
```

### Reproduction Steps

* Use cluster url in the connection string
* Set plugins to either `auroraHostList,readWriteSplitting` or `readWriteSplitting,failover,efm`
* Startup the application

### Possible Solution

`HikariPooledConnectionProvider` works only for urls of type `RdsUrlType.RDS_INSTANCE`, but `RDS_WRITER_CLUSTER` url is supplied by the wrapper.

### Additional Information/Context

The behavior is identical no matter what set of plugins I use, be it `readWriteSplitting,failover,efm` or `auroraHostList,readWriteSplitting`

### The AWS Advanced JDBC Driver version used

2.1.2

### JDK version used

17.0.7

### Operating System and version

Linux pop-os 6.2.6-76060206-generic #202303130630~1683753207~22.04~77c1465 SMP PREEMPT_DYNAMIC Wed M x86_64 x86_64 x86_64 GNU/Linux

**Comment by crystall-bitquill** [comment]
Hi @firebike,

Thanks for reaching out and raising this issue.

We'll take a look at this and keep you updated as we investigate.

Thank you for your patience!

**Comment by congoamz** [comment]
Hi @firebike, thanks for reaching out. With the current code we intentionally avoid creating a connection pool for cluster URLs. This is because it may be problematic to create a pool for a URL that can resolve to different instances over time. Currently, the main benefit of internal pools is when setReadOnly is called. When setReadOnly is called (regardless of the initial connection URL), an internal pool will be created for the writer/reader that the plugin switches to and connections for that instance can be reused in the future. In general, initial connections won't be pooled unless the user supplies an instance URL.

**Comment by datenbrille** [comment]
@congoamz What is the preferred configuration for this setup as in regards to the urls etc. We have a 2 nodes setup with one reader and one writer.

**Comment by firebike** [comment]
@congoamz Thank you for this explanation. My incorrect understanding was that I can now fully delegate connection pool management to the aws-wrapper driver. However, as it is not the case, I still have to maintain the connection pool in the application. The good thing is that I can now keep a singe pool for both reader and writer connections and ditch custom routing datasource from the codebase.
After reworking the setup I can confirm that:
* The application connection pool creates WRITER connections using writer cluster url that I've provided in the JDBC Url.  :+1: 
* The aws-wrapper creates READER connections using discovered reader instance url :+1: 
* The READER connections are pooled :+1: 

I'm gonna test failover switching next.

**Comment by congoamz** [comment]
> @congoamz What is the preferred configuration for this setup as in regards to the urls etc. We have a 2 nodes setup with one reader and one writer.

Hi @datenbrille, I suggest you use the cluster URLs because they track the roles (writer or reader) of the instances after failover events (which can cause instance roles to change). If the connection you are requesting will only be performing reads you can use the reader cluster URL, otherwise you can use the writer cluster URL. You can also call setReadOnly on the connection object to switch to an instance with a different role later on. Note that the initial connection will not be pooled when you use cluster URLs. However, when setReadOnly is called, an internal pool will be created for the writer/reader that the plugin switches to and connections for that instance can be reused by future setReadOnly calls.

**Comment by firebike** [comment]
I can confirm that the failover switch worked flawlessly. The connections were re-established in seconds. :+1:
