### ISSUE TITLE
Why does this have to be a TopologyAwareDatabaseCluster

### ISSUE THREAD

**Issue by davecramer** [awslabs/aws-advanced-jdbc-wrapper#487]
https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/4b166ede0c06bceec22da6280754d3ab710881ab/wrapper/src/main/java/software/amazon/jdbc/plugin/staledns/AuroraStaleDnsHelper.java#L87

All dialects should support isReadOnly.

**Comment by crystall-bitquill** [comment]
Closing this ticket now because the AuroraStaleDnsHelper has been updated and no longer includes the check in question.
