### ISSUE TITLE
Lack of clarity regarding configuration of driver wrapper for use with Spring and HikariCP

### ISSUE THREAD

**Issue by benrebakpublic** [awslabs/aws-advanced-jdbc-wrapper#490]
### Describe the issue

From HikariCP's own documentation for [configuring Hikari with Spring](https://github.com/brettwooldridge/HikariCP/blob/dev/README.md):

> ⚠ Note: Spring Boot auto-configuration users, you need to use jdbcUrl-based configuration.

Based on my understanding, this means providing the following two properties (in addition to username/password):

```
spring.datasource.driver-class-name
spring.datasource.url
```

Yet from the documentation for [configuring the wrapper with HikariCP](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/DataSource.md#hikaricp-pooling-example): 

> ⚠️Note: HikariCP supports either DataSource-based configuration or DriverManager-based configuration by specifying the dataSourceClassName or the jdbcUrl. When using the AwsWrapperDataSource you must specify the dataSourceClassName, therefore HikariDataSource.setJdbcUrl is not supported. For more information see HikariCP's [documentation](https://github.com/brettwooldridge/HikariCP#gear-configuration-knobs-baby).

which means providing (in addition to username/password):

```
spring.datasource.hikari.data-source-class-name
```

These two statements taken together seem to imply that using the AWS wrapper prevents Hikari from being able to autoconfigure a Spring datasource.

I would appreciate a complete example of how to configure a DataSource using Spring properties, HikariCP AND the AWS advanced JDBC wrapper. I.e. what Spring / Hikari / properties are required in order for the DataSource to be configured as in the [Hikari example](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/DataSource.md#hikaricp-pooling-example), with failover and efm enabled.

### Links

https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/DataSource.md#hikaricp-pooling-example

**Comment by aaronchung-bitquill** [comment]
Hi @benrebakpublic 

Thanks for reaching out and raising this.

Coincidentally, I recently started working on an example of how to confiture a DataSource using Spring Boot, HikariCP , and the AWS Advanced JDBC Wrapper. 

Here is the Pull Request: https://github.com/awslabs/aws-advanced-jdbc-wrapper/pull/485

Thank you for your patience!

**Comment by benrebakpublic** [comment]
Hi @aaronchung-bitquill ,

Thanks, the example in your PR got me started. My app is now running, and I've been able to throw a lot of my abysmal attempt away.

I'd like to verify that the `AwsWrapperDataSource` is being used, but when I add

```
logging.level.software.amazon.jdbc.Driver=TRACE
logging.level.software.amazon.jdbc.AwsWrapperDataSource=TRACE
```

to my application.properties, I'm not seeing any additional logging. Any advice?

**Comment by aaronchung-bitquill** [comment]
Hi @benrebakpublic 

For enabling driver logs, please take a look at [the section of the documentation on enabling logging.]((https://github.com/awslabs/aws-mysql-jdbc#enable-logging). ) 

Thanks you!

**Comment by benrebakpublic** [comment]
Hi @aaronchung-bitquill.

I followed the documentation, but I wasn't able to get any more detailed logging about the driver being configured. I'm closing this issue, but I'm still lacking insight into what's actually being configured within my Spring app by the (extremely helpful) example you've provided of how to configure this driver with Spring & Hikari.
