### ISSUE TITLE
Change in Maven packaging?

### ISSUE THREAD

**Issue by ethanmills** [awslabs/aws-advanced-jdbc-wrapper#491]
### Describe the bug

When changing our dependency coordinates from  
`implementation("software.amazon.jdbc:aws-advanced-jdbc-wrapper:2.1.2")`
to
`implementation("software.amazon.jdbc:aws-advanced-jdbc-wrapper:2.2.0")`
gradle has resolved a new plain jar file. This does not contain the library, but rather the SpingWildflyExampleApplication.

See the difference between 2.1.2 and 2.2.0 in the screenshots
![image](https://github.com/awslabs/aws-advanced-jdbc-wrapper/assets/40488007/a4769dad-705b-431a-8801-e32f6767dea9)
![image](https://github.com/awslabs/aws-advanced-jdbc-wrapper/assets/40488007/4c9e4ea2-b7a5-4162-acd8-1672a43bd060)

The difference in artefacts can be seen by comparing
https://repo1.maven.org/maven2/software/amazon/jdbc/aws-advanced-jdbc-wrapper/2.1.2/
to
https://repo1.maven.org/maven2/software/amazon/jdbc/aws-advanced-jdbc-wrapper/2.2.0/

This clearly doesn't work, as no library code is loaded

### Expected Behavior

Correct jar is located

### What plugins are used? What other connection properties were set?

-

### Current Behavior

-

### Reproduction Steps

-

### The AWS Advanced JDBC Driver version used

2.2.0

### JDK version used

17

### Operating System and version

Windows

**Comment by ethanmills** [comment]
I think this may be because 
https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/examples/SpringWildflyExample/spring/build.gradle.kts
is in a different dir to
https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/examples/SpringWildflyExample/gradle.properties

**Comment by hsuamz** [comment]
Thank you for raising this. We will be working on a resolution to this and provide updates when available.

**Comment by crystall-bitquill** [comment]
Hi @ethanmills,

[Version 2.2.1](https://search.maven.org/artifact/software.amazon.jdbc/aws-advanced-jdbc-wrapper/2.2.1/jar?eh=) of the AWS JDBC Driver has been released to address this problem. Please let us know if you have any further issues, thank you!

**Comment by ethanmills** [comment]
That's looking good @crystall-bitquill , thanks for the fix!
