### ISSUE TITLE
Document how to use this with no plugins

### ISSUE THREAD

**Issue by davecramer** [awslabs/aws-advanced-jdbc-wrapper#494]
### Describe the feature

I want to use the driver with vanilla PostgreSQL or MySQL

### Use Case

same as above

### Proposed Solution

We will have to add the `defaultPlugin` to accepted names for plugins so the user can load only that plugin.
Need to document and provide an example for users.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### The AWS Advanced JDBC Driver version used

2.1.2

### JDK version used

1.8

### Operating System and version

macos

**Comment by karenc-bq** [comment]
We have documentation on how to disable plugins: https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/UsingTheJdbcDriver.md#:~:text=Provide%20an%20empty%20string%20to%20disable%20all%20plugins%3A

**Comment by brunos-bq** [comment]
Docs have a small section instructing users to use an empty string for `wrapperPlugins` to have a vanilla JDBC driver experience.

https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/UsingTheJdbcDriver.md#connection-plugin-manager-parameters

Is that OK or does it need a different highlight or location @davecramer ??
