### ISSUE TITLE
Veracode findings

### ISSUE THREAD

**Issue by Original-Adam** [awslabs/aws-advanced-jdbc-wrapper#495]
Hello,

Veracode scan of our application found those code quality flaws:

![image](https://github.com/awslabs/aws-advanced-jdbc-wrapper/assets/137061577/d138e713-fa6a-49f9-be7c-d67d9b69727a)

![image](https://github.com/awslabs/aws-advanced-jdbc-wrapper/assets/137061577/60eeeea2-2237-4fd0-8033-bc5fa5ae2c4d)

If it's possible please address those issues

**Comment by hsuamz** [comment]
Hello @Original-Adam,

Thanks for reaching out and sharing your findings. We'll investigate into this and provide an update when available.

Thanks,

Matthew

**Comment by aaronchung-bitquill** [comment]
Hi @Original-Adam ,

We have evaluated the code cited by Veracode and have concluded that the identified flaws can be safely marked as false positives. 

Veracode cites "Improper Resource Shutdown or Relase". However in all the cited code locations, all resources are either stored in a wrapper object, or returned as result. 

For example, the [CallableStatementWrapper](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/wrapper/src/main/java/software/amazon/jdbc/wrapper/CallableStatementWrapper.java) class as its name suggests, is a wrapper object around `CallableStatement`. As such, the `close()` method to release the wrapped resource `CallableStatement`, will be released when corresponding `close()` method is called on `CallableStatementWrapper` like [this](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/wrapper/src/main/java/software/amazon/jdbc/wrapper/CallableStatementWrapper.java#L120). Then whatever consuming code will be responsible for calling the `close()` method to intiate releasing the resource.  

Also in the cited code location (CallableStatementWrapper.java:242)[https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/wrapper/src/main/java/software/amazon/jdbc/wrapper/CallableStatementWrapper.java#L242], the results directly returned. 

All of the identified flaws follow the same pattern as the above.

Please let us know if you have any questions and concerns about this or anything else. 

Thank you

**Comment by Original-Adam** [comment]
Hey,
The explanation you have given is sufficient and we'll mark those as false positives.
Thank you for the quick response.
