### ISSUE TITLE
Update repo Wiki to match documentation in docs/

### ISSUE THREAD

**Issue by lily-es** [awslabs/aws-advanced-jdbc-wrapper#498]
### Describe the issue

The repo's Wiki is outdated in regards to the documentation in docs/
An example is the DataSource documentation.

### Links

https://github.com/awslabs/aws-advanced-jdbc-wrapper/wiki/DataSource

**Comment by karenc-bq** [comment]
Hi @lily-es, thank you for raising this issue, we have updated the wiki. Please let us know if you notice any more discrepancies.

**Comment by karenc-bq** [comment]
Hi @lily-es, we will be closing this ticket now, thank you again for raising this issue.
