### ISSUE TITLE
Port Number is a non-existent property. 

### ISSUE THREAD

**Issue by jrobe** [awslabs/aws-advanced-jdbc-wrapper#503]
https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/319ea9efc4336d7d064342792bac5ea0e88f7b28/examples/HikariExample/src/main/java/software/amazon/HikariFailoverExample.java#L50

Doc should be changed to "serverPort".

**Comment by crystall-bitquill** [comment]
Hi @jrobe,

Thanks for raising this issue, we've updated the example (#504). Please let us know if you notice any more discrepancies.
