### ISSUE TITLE
Documentation specifies the wrong version for Maven

### ISSUE THREAD

**Issue by larmitage-nex** [awslabs/aws-advanced-jdbc-wrapper#574]
### Describe the issue

The documentation gives the example 
```
<dependencies>
    <dependency>
        <groupId>software.amazon.jdbc</groupId>
        <artifactId>aws-advanced-jdbc-wrapper</artifactId>
        <version>2.2.3</version>
    </dependency>
</dependencies>
```
but version 2.2.3 has not been published on Maven yet (as of time of writing)

Is this automatically updated? It would be better if it is updated only once published to Maven

### Links

https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/GettingStarted.md#as-a-maven-dependency

**Comment by crystall-bitquill** [comment]
Hi @larmitage-nex, thanks for raising this issue. We've updated the documentation to reflect the latest version. We'll be closing this ticket now, but please let us know if you notice any other discrepancies.
