### ISSUE TITLE
How to configure a wrapper plugin when using AwsWrapperDataSource

### ISSUE THREAD

**Issue by KyleAure** [awslabs/aws-advanced-jdbc-wrapper#604]
### Describe the issue

There are no examples of using wrapper plugins with a AwsWrapperDataSource. 
The DataSource.md page shows how to configure a DataSource, but doesn't show how I would provide plugin configuration.

For example if I wanted to use AWS Secrets Manager how do I configure the DataSource with `secretsManagerSecretId` and `secretsManagerRegion`? 

There are no setters on the AwsWrapperDataSource for these properties. 
And the `setTargetDataSourceProperties` method only propgates datasource properties to the underlying driver which doesn't support the AWS Secret Manager.

From the documentation and classes it doesn't seem the AwsWrapperDataSource can accomplish this task. 

### Links

https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/a970aecd704faadade0b449f3de9fc9f6b54e090/docs/using-the-jdbc-driver/DataSource.md?plain=1#L76

**Comment by crystall-bitquill** [comment]
Hi @KyleAure,

Thanks for reaching out and raising this issue.

We have a few examples on using the AwsWrapperDataSource in our [documentation](https://github.com/awslabs/aws-advanced-jdbc-wrapper#examples):
- [Simple AwsWrapperDataSource example](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/examples/AWSDriverExample/src/main/java/software/amazon/DatasourceExample.java)
- [HikariCP AwsWrapperDataSource example](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/examples/HikariExample/src/main/java/software/amazon/HikariExample.java)

We do use the `setTargetDataSourceProperties` method to configure plugins such as the AWS Secrets Manager plugin.

This is an example of configuring the AwsWrapperDataSource with the AWS Secrets Manager plugin:
```java
AwsWrapperDataSource ds = new AwsWrapperDataSource();

// Configure the property names for the underlying driver-specific data source:
ds.setJdbcProtocol("jdbc:postgresql:");

// Specify the driver-specific data source:
ds.setTargetDataSourceClassName("org.postgresql.ds.PGSimpleDataSource");

Properties targetDataSourceProps = new Properties();
targetDataSourceProps.setProperty("wrapperPlugins", "awsSecretsManager");
targetDataSourceProps.setProperty("serverName", "db-identifier.cluster-XYZ.us-east-2.rds.amazonaws.com");
targetDataSourceProps.setProperty("database", "employees");
targetDataSourceProps.setProperty("serverPort", "5432");
targetDataSourceProps.setProperty("secretsManagerSecretId", "secretId");
targetDataSourceProps.setProperty("secretsManagerRegion", "us-east-2");
ds.setTargetDataSourceProperties(targetDataSourceProps);
```

And in case you're using HikariCP, the equivalent configuration would look like this:
```java
HikariDataSource ds = new HikariDataSource();

// Specify the underlying datasource for HikariCP:
ds.setDataSourceClassName(AwsWrapperDataSource.class.getName());

// Configure AwsWrapperDataSource:
ds.addDataSourceProperty("jdbcProtocol", "jdbc:postgresql:");
ds.addDataSourceProperty("database", "employees");
ds.addDataSourceProperty("serverPort", "5432");
ds.addDataSourceProperty("serverName", "db-identifier.cluster-XYZ.us-east-2.rds.amazonaws.com");

// Specify the driver-specific data source for AwsWrapperDataSource:
ds.addDataSourceProperty("targetDataSourceClassName", "org.postgresql.ds.PGSimpleDataSource");

Properties targetDataSourceProps = new Properties();
targetDataSourceProps.setProperty("wrapperPlugins", "awsSecretsManager");
targetDataSourceProps.setProperty("secretsManagerSecretId", "secretId");
targetDataSourceProps.setProperty("secretsManagerRegion", "us-east-2");

ds.addDataSourceProperty("targetDataSourceProperties", targetDataSourceProps);
```

**Comment by KyleAure** [comment]
@crystall-bitquill Thanks for the clarification.  

When reading through the documentation I assumed that the field `targetDataSourceProperties` were only for properties to be set on the underlying datasource and not to configure the `AwsWrapperDataSource`.  I do think this could be better documented with examples. 

I tested it out and was able to see these properties getting used by the `AwsWrapperDataSource`.

**Comment by crystall-bitquill** [comment]
Thanks for the suggestion, I've opened a [PR](https://github.com/awslabs/aws-advanced-jdbc-wrapper/pull/606) to make the documentation a bit clearer.

**Comment by crystall-bitquill** [comment]
Hi @KyleAure,

Just wanted to let you know that we've merged the documentation changes. This ticket will be closed now but please feel free to reopen this issue or to create a new one if you have any other questions or concerns.

Thank you!
