### ISSUE TITLE
Add endpoint configurability to AWS Secrets Manager Plugin

### ISSUE THREAD

**Issue by pennytextures** [awslabs/aws-advanced-jdbc-wrapper#630]
### Describe the feature

It would be nice if the secrets manager plugin would take some configuration via properties to use an endpoint, like so:

secretsManagerEndpoint: http://localhost:4566

This would allow it to work with secrets manager running from localstack.

### Use Case

We'd like to use the jdbc wrapper, but in development environments against localstack we'd have to reimplement our own aws secrets manager plugin and make the endpoint configurable, it'd be much nicer if we could just do this via a property.

### Proposed Solution

`  public static final AwsWrapperProperty ENDPOINT_PROPERTY = new AwsWrapperProperty(
      "secretsManagerEndpoint", null,
      "The secrets manager endpoint of the secret to retrieve.");`
      
 Then if this property isn't null, include it in the client builder

### Other Information

This wouldn't be an issue if we developed against real aws resources, but at the scale of our project this is not financially viable.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### The AWS Advanced JDBC Driver version used

2.2.4

### JDK version used

17.0.8

### Operating System and version

amazoncorretto:17.0.8-al2

**Comment by crystall-bitquill** [comment]
Hi @pennytextures,

Thanks for reaching out and raising this issue.

We'll take a look at this and keep you updated as we investigate.

Thank you for your patience!

**Comment by crystall-bitquill** [comment]
Hi @pennytextures,

We've recently merged some changes to add this feature (#707). Could you kindly check out our latest [snapshot build](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/UsingTheJdbcDriver.md#using-a-snapshot-of-the-driver) and let us know if the changes work for you?

Thank you!

**Comment by pennytextures** [comment]
i’ll try and revive our attempt to integrate it with our codebase next week :)On 17 Nov 2023, at 21:15, crystall-bitquill ***@***.***> wrote:﻿
Hi @pennytextures,
I wanted to check in and see if you were able to verify the endpoint configurability was working. If there are no further updates on this ticket in the next few days, it will be closed. However, if you have any other questions or concerns please feel free to reopen this issue or to create a new one.
Thank you!
