### ISSUE TITLE
exception when logging enabled

### ISSUE THREAD

**Issue by mnoky** [awslabs/aws-advanced-jdbc-wrapper#633]
### Describe the bug

I have a Spring Boot application that is using the wrapper. Everything works fine but when I enable logging by setting the driver parameter `wrapperLoggerLevel` to `FINEST` an exception happens when the application starts up. It looks like the exception happens the first time logging is invoked. It seems the `messages.properties` file somehow did not get loaded properly in the [Messages class](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/wrapper/src/main/java/software/amazon/jdbc/util/Messages.java) and thus the message `TargetDriverDialectManager.useDialect` could not be found.

The stack trace is:
```
java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key TargetDriverDialectManager.useDialect
  at java.base/java.util.ResourceBundle.getObject(Unknown Source)
  at java.base/java.util.ResourceBundle.getString(Unknown Source)
  at software.amazon.jdbc.util.Messages.get(Messages.java:38)
  at software.amazon.jdbc.targetdriverdialect.TargetDriverDialectManager.lambda$logDialect$3(TargetDriverDialectManager.java:120)
  at java.logging/java.util.logging.Logger.log(Unknown Source)
  at java.logging/java.util.logging.Logger.finest(Unknown Source)
  at software.amazon.jdbc.targetdriverdialect.TargetDriverDialectManager.logDialect(TargetDriverDialectManager.java:120)
  at software.amazon.jdbc.targetdriverdialect.TargetDriverDialectManager.getDialect(TargetDriverDialectManager.java:109)
  at software.amazon.jdbc.targetdriverdialect.TargetDriverDialectManager.getDialect(TargetDriverDialectManager.java:70)
  at software.amazon.jdbc.Driver.connect(Driver.java:144)
...
```

Note that my application normally logs with logback/slf4j; I have added `jul-to-slf4j` to `pom.xml` to enable `java.util.logging` over slf4j.

### Expected Behavior

I would expect the application to find log messages in `messages.properties` without causing an exception

### What plugins are used? What other connection properties were set?

plugins: iam. properties: wrapperLoggerLevel=FINEST, wrapperDialect=rds-pg, ssl properties for postgresql

### Current Behavior

See above for stack trace

### Reproduction Steps

No simple way to reproduce

### The AWS Advanced JDBC Driver version used

2.2.4

### JDK version used

17

### Operating System and version

Alpine Linux via Docker image: eclipse-temurin:17.0.8_7-jre-alpine

**Comment by crystall-bitquill** [comment]
Hi @mnoky,

Thanks for reaching out and raising this issue.

We'll take a look at this and keep you updated as we investigate.

Thank you for your patience!

**Comment by ashihara-sst** [comment]
I had the same problem since the driver's `ResourceBundle.getBundle("messages")` loaded my project `messages.properties`.

I simply solved the problem by renaming my `messages.properties` to another name.

**Comment by crystall-bitquill** [comment]
Hi,

Thank you @ashihara-sst for suggesting a fix!

Have you had the chance to try this solution, @mnoky?

And to update both of you, we've renamed the `messages.properties` file in this [PR](https://github.com/awslabs/aws-advanced-jdbc-wrapper/pull/647) to avoid similar issues. This change is available in the latest [snapshot build](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/UsingTheJdbcDriver.md#using-a-snapshot-of-the-driver).

**Comment by crystall-bitquill** [comment]
Thanks for confirming that the fix works! This issue will be closed now, but please feel free to reach out again if there are any other questions or concerns.
