### ISSUE TITLE
Missing state(s) on failover

### ISSUE THREAD

**Issue by davecramer** [awslabs/aws-advanced-jdbc-wrapper#649]
https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/51ce0b4e0a479f7920582e771dae23b73a2dfcad/wrapper/src/main/java/software/amazon/jdbc/plugin/failover/FailoverConnectionPlugin.java#L502

We should probably be doing something like
https://github.com/brettwooldridge/HikariCP/blob/8c1a7c29341348b3ea71ccfe35d4858b378160e2/src/main/java/com/zaxxer/hikari/pool/PoolBase.java#L205

**Comment by scott-long-adp** [comment]
Thanks Dave -- yes taking an approach closer to the hikari PoolBase would help us a lot in being able to adopt the wrapper driver for MySql.  Perhaps even better would be giving us the ability to provide a listener or lambda to initialize a connection on failover ourselves.  

Currently these two methods in the FailoverConnectionPlugin will attempt to restore autoCommit, readOnly, and in some cases transactionIsolation during a connection switch, but from looking at PoolBase, a lot more properties are initialized.   

software.amazon.jdbc.plugin.failover.FailoverConnectionPlugin#transferSessionState
software.amazon.jdbc.plugin.failover.FailoverConnectionPlugin#restoreSessionState

Being able to ensure proper initialization in both cases would be valuable. 

If AWS Wrapper directly implemented the equivalent of Hikari PoolBase, that may be sufficient.  But as it may be out of scope for the AWS Wrapper driver to know all possible connection setup scenarios, it may also be worthwhile if the AWS Wrapper driver provided some means for us to intercept and perform the connection setup using a listener or provided lambda of some sort.

Do you have an expected timeframe to deliver this capability?  Either giving driver consumers access to connection setup, or duplicating the current Hikari connection setup in the wrapper driver so all consumers of the wrapper driver can use it?

thanks,
- scott

**Comment by davecramer** [comment]
@scott-long-adp Does https://github.com/awslabs/aws-advanced-jdbc-wrapper/pull/705 help in this case ?

**Comment by scott-long-adp** [comment]
@davecramer possibly -- does it address all places where session state is configured or copied?  I am thinking specifically of:

software.amazon.jdbc.plugin.failover.FailoverConnectionPlugin#transferSessionState --and--
software.amazon.jdbc.plugin.failover.FailoverConnectionPlugin#restoreSessionState

... these two methods appear to be invoked during certain failover scenarios and do some setup of the connection-- is the intent that ConnectionProviderManager.setConnectionInitFunc() replace these?  It looks like they are both still active whether setConnectionInitFunc() is used or not.

**Comment by davecramer** [comment]
@scott-long-adp we have a more comprehensive PR in flight https://github.com/awslabs/aws-advanced-jdbc-wrapper/pull/729/

**Comment by karenc-bq** [comment]
Closing issue as #729 has been merged and released in [v2.3.1](https://github.com/awslabs/aws-advanced-jdbc-wrapper/releases/tag/2.3.1).
