### ISSUE TITLE
Memory Leak in EFM Plugin

### ISSUE THREAD

**Issue by chr-fritz** [awslabs/aws-advanced-jdbc-wrapper#675]
### Describe the bug

In our application we've two aurora databases each with an own jdbc connection. Through our monitoring we found that our pods randomly restarted due to out of memory. After some investigation we found out that the `software.amazon.jdbc.plugin.efm.MonitorImpl` of one of our jdbc connections stopped working and we don't saw any exceptions. In this case it collects `software.amazon.jdbc.plugin.efm.MonitorConnectionContext` objects in the `newContexts` queue. In one of our heap dumps we found out that in the `newContexts` queue were over 4000000 objects.

This screenshot from one of our heap show that the first instance is `stopped=true` with over 411MB of objects in the `newContexts` queue. The second one is the one which is working it no objects in the `newContexts` queue.
<img width="1263" alt="grafik" src="https://github.com/awslabs/aws-advanced-jdbc-wrapper/assets/1180400/e0469a70-e559-4df4-b585-3e8473f2b17a">

### Expected Behavior

No memory leak.

### What plugins are used? What other connection properties were set?

auroraConnectionTracker,failover,efm,iam

### Current Behavior

Randomly the Monitor stopps and objects are stored in `newContexts` but they won't ever be removed.

### Reproduction Steps

We couldn't find any reproducer as we just observed this behavior randomly without any pattern.

### Possible Solution

At least catch and log `RuntimeException` and return an appropriate `ConnectionStatus` object in `software.amazon.jdbc.plugin.efm.MonitorImpl#checkConnectionStatus` to avoid that uncaught runtime exceptions stop the monitoring thread without shutting down the monitor completly.

### The AWS Advanced JDBC Driver version used

2.2.2

### JDK version used

zulu 11.0.17

### Operating System and version

Distroless Docker Image at AWS EKS

**Comment by crystall-bitquill** [comment]
Hi @chr-fritz,

Thanks for reaching out and raising this issue.

We'll take a look at this and keep you updated as we investigate.

Thank you for your patience!

**Comment by crystall-bitquill** [comment]
Hi @chr-fritz,

We've recently merged some changes (PR #676) that updated our monitoring implementation and added additional logging. I understand that you aren't able to reproduce this consistently, but would you be able to check out our [snapshot build](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/UsingTheJdbcDriver.md#using-a-snapshot-of-the-driver) with driver logs enabled (logs can be enabled as seen [here](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/UsingTheJdbcDriver.md#logging)) and let us know how that goes?

Thank you!

**Comment by andrecloutier-pd** [comment]
Hey @crystall-bitquill,

I'm also experiencing the same issue reported here. I've using a snapshot build and getting the following log line (identifying details removed). I'm thinking we need to include the exception type in the log line.

```
WARNING: Continuing monitoring after unhandled exception was thrown in monitoring thread for node <clustername>-02.<removed>.us-west-2.rds.amazonaws.com: null
Nov 14, 2023 9:23:23 PM software.amazon.jdbc.plugin.efm.MonitorImpl run
```

**Comment by crystall-bitquill** [comment]
Hi @andrecloutier-pd,

Thanks for trying out the snapshot build and for letting us know about the logs. There were some changes merged recently (PR #718) that make the logger message include the entire exception. Could you kindly check out the latest snapshot build and let us know how that goes?

Thank you!

**Comment by kimble** [comment]
![costly](https://github.com/awslabs/aws-advanced-jdbc-wrapper/assets/90724/dd3a7875-68b3-4a6b-96d6-dfc62ca017c8)

I wonder if this is the same issue? Two days ago we got a budget warning from AWS. Something had generated a few gigabytes (or hundreds of dollars depending on how you want to measure it) of cloudwatch log entries. The CPU was spinning on 100% generating the output in the image as fast as it could. 

No wonder AWS is big business for Amazon

**Comment by karenc-bq** [comment]
Hi @kimble, thank you for reaching out with this information.

The driver logs thrown by the monitoring thread are necessary to inform the user of potential monitoring problems. This info can help the user and team diagnose and address issues that may arise. However, we understand that the volume of logs generated by this particular scenario was greater than you expected. To address this, we have created PR #751, which lowers the logging level for the particular messages you are seeing to avoid potential surprises for other customers. Thank you for raising your concern. Please note that you can also [filter the logs using the properties file](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/UsingTheJdbcDriver.md#logging). For example, to filter out the logs in the posted image you can add the following line to your `.properties` file:
```
software.amazon.jdbc.plugin.efm.MonitorImpl.level=OFF
```

Regarding the memory leaks issue, we have made improvements to the monitoring objects to ensure they are synchronized and the driver does not cache references to them in PR #718.
We will keep you updated for when we create an official release containing this fix.

In the meantime, could you please help us further improve our driver by checking out our [snapshot build](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/UsingTheJdbcDriver.md#using-a-snapshot-of-the-driver) containing changes from PR #751 and PR #718, and send us the unhandled exceptions your application is throwing so we can triage it?

**Comment by kimble** [comment]
> Hi @kimble, thank you for reaching out with this information.
> 
> The driver logs thrown by the monitoring thread are necessary to inform the user of potential monitoring problems. This info can help the user and team diagnose and address issues that may arise. However, we understand that the volume of logs generated by this particular scenario was greater than you expected. To address this, we have created PR #751, which lowers the logging level for the particular messages you are seeing to avoid potential surprises for other customers. Thank you for raising your concern. Please note that you can also [filter the logs using the properties file](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/UsingTheJdbcDriver.md#logging). For example, to filter out the logs in the posted image you can add the following line to your `.properties` file:
> 
> ```
> software.amazon.jdbc.plugin.efm.MonitorImpl.level=OFF
> ```
> 
> Regarding the memory leaks issue, we have made improvements to the monitoring objects to ensure they are synchronized and the driver does not cache references to them in PR #718. We will keep you updated for when we create an official release containing this fix.
> 
> In the meantime, could you please help us further improve our driver by checking out our [snapshot build](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/UsingTheJdbcDriver.md#using-a-snapshot-of-the-driver) containing changes from PR #751 and PR #718, and send us the unhandled exceptions your application is throwing so we can triage it?

Reducing the log level will probably just hide the problem that there is a thread consuming 100% printing the lines from my screenshot over and over as fast as it can. 

> and send us the unhandled exceptions your application is throwing

Not sure what you mean by this?

**Comment by karenc-bq** [comment]
Hi @kimble,

1. The logs will only be printed if you choose to enable `FINEST/DEBUG` level logs. You can also disable logging for that particular thread.
2. We have released [v2.3.1](https://github.com/awslabs/aws-advanced-jdbc-wrapper/releases) containing fixes from #751 and #718. Could you please give it a try? If the issue persists can you please send us the driver logs related to the issue?

**Comment by crystall-bitquill** [comment]
Hi all,

We've recently added an **experimental** Host Monitoring Plugin (PR #764) to the driver, called the Host Monitoring Plugin v2. More information can be found [here](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/using-plugins/UsingTheHostMonitoringPlugin.md#experimental-host-monitoring-plugin-v2). The Host Monitoring Plugin v2 is functionally equivalent to the Host Monitoring Plugin and they are configured using the same parameters. The Host Monitoring Plugin v2 was created to address the issues that you all have been experiencing, and it is meant to be a more stable version of the Host Monitoring Plugin.

As it is currently an experimental plugin, please note that it should be tested before being used in a production environment. This plugin can be tried out by using the snapshot build [`aws-advanced-jdbc-wrapper-2.3.2-20231213.213138-10.jar`](https://aws.oss.sonatype.org/content/repositories/snapshots/software/amazon/jdbc/aws-advanced-jdbc-wrapper/2.3.2-SNAPSHOT/). For more information on using a snapshot build, see [this page](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/UsingTheJdbcDriver.md#using-a-snapshot-of-the-driver). If you are able to test out the plugin, please let us know if you encounter any errors or if this plugin was able to resolve the issues you've encountered.

Thank you!

**Comment by aaronchung-bitquill** [comment]
Hi all,

Heads up that the aforementioned experimental Host Monitoring Plugin is now available on our [latest release of the driver](https://search.maven.org/artifact/software.amazon.jdbc/aws-advanced-jdbc-wrapper/2.3.2/jar).

Also wanted to reiterate that it is currently an experimental plugin that should be tested before being used in a production environment. 

If you are able to test out the plugin, please let us know if it resolves these issues or if there are any other issues encountered. 

Thank you

**Comment by aaronchung-bitquill** [comment]
Hi all,

Heads up that the aforementioned experimental Host Monitoring Plugin is now available on our [latest release of the driver](https://search.maven.org/artifact/software.amazon.jdbc/aws-advanced-jdbc-wrapper/2.3.2/jar).

Also wanted to reiterate that it is currently an experimental plugin that should be tested before being used in a production environment.

If you are able to test out the plugin, please let us know if it resolves these issues or if there are any other issues encountered.

Thank you
