### ISSUE TITLE
ClusterAwareReaderFailoverHandler logs database password in FINE mode

### ISSUE THREAD

**Issue by basanthjenuhb** [awslabs/aws-advanced-jdbc-wrapper#693]
### Describe the bug

The ClusterAwareReaderFailoverHandler works fine in itself.
But it logs password which comes as part of `initialConnectionProps` object

https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/wrapper/src/main/java/software/amazon/jdbc/plugin/failover/ClusterAwareReaderFailoverHandler.java#L393-L396

### Expected Behavior

Password should not be logged

### What plugins are used? What other connection properties were set?

wrapperLoggerLevel, FINE

### Current Behavior

```
[2023-10-22T16:05:48,157+0000] FINE   software.amazon.jdbc.plugin.failover.ClusterAwareReaderFailoverHandler$ConnectionAttemptTask call Trying to connect to reader: 'rc-e2e-cache-shard-011.chwwa50qyp7z.us-west-2.rds.amazonaws.com:5432/', with properties '{failoverTimeoutMs=10000, password=my-password, database=perf, wrapperLogUnclosedConnections=true, wrapperLoggerLevel=FINE, user=perf_user}'
```
Logs seen

### Reproduction Steps

just setting logging level to FINE, and causing a failover

### The AWS Advanced JDBC Driver version used

2.2.5

### JDK version used

11

### Operating System and version

Linux

**Comment by brunos-bq** [comment]
Hello @basanthjenuhb,

We have just merged in a fix. Could you kindly checkout our [snapshot](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/UsingTheJdbcDriver.md#using-a-snapshot-of-the-driver) build and let us know if the issue still persists?

Thank you!

**Comment by crystall-bitquill** [comment]
Hi @basanthjenuhb,

To update you, the changes for this issue have been included in the [latest release of the driver](https://search.maven.org/artifact/software.amazon.jdbc/aws-advanced-jdbc-wrapper/2.3.0/jar?eh=). We'll be closing this ticket now, but please feel free to reopen this issue or to create a new one if you have other questions or concerns.

Thank you!
