### ISSUE TITLE
Continuing monitoring after unhandled exception was thrown in monitoring causes High CPU load

### ISSUE THREAD

**Issue by truskare** [awslabs/aws-advanced-jdbc-wrapper#752]
### Describe the bug

After upgrading to version 2.3.0 we have started to get loads of the following log entries:

```
WARNING: Continuing monitoring after unhandled exception was thrown in monitoring thread for node : null                      
software.amazon.jdbc.plugin.efm.MonitorImpl run
```

This again causes full CPU load on the application. The issue only seems to start after a while (10-20hours?) and when the application goes idle (when there is no active queries against the database). When the new queries starts again the issue goes away, but occurs again  when the application idles again etc.

We can also see the following log messages sporadically before the issue above:

`WARNING: Monitoring was already stopped for node 
software.amazon.jdbc.plugin.efm.MonitorImpl startMonitoring`

This issue occurs with awssdk v2.17.290, 2.21.24, 2.21.28. Postgres 14.3, 14.5 and 15.3

### Expected Behavior

To not have any issues. Like in v2.2.5. 

### What plugins are used? What other connection properties were set?

iam and efm and hikari

### Current Behavior

WARNING: Continuing monitoring after unhandled exception was thrown in monitoring thread for node : null                      
software.amazon.jdbc.plugin.efm.MonitorImpl run

### Reproduction Steps

Start application with some traffic. wait for a while (10-20hours?) and stop traffic (database queries). 

### The AWS Advanced JDBC Driver version used

2.3.0

### JDK version used

OpenJDK17

### Operating System and version

Red Hat Universal Base Image 8

**Comment by brunos-bq** [comment]
Hi @truskare,

Thanks for reaching out and raising this issue.

We'll take a look at this and keep you updated as we investigate.

Thank you for your patience!

**Comment by brunos-bq** [comment]
Hello @truskare,

In version 2.3.1, we have altered the log level of some monitoring actions from `WARNING` to `FINEST`. We suggest you to try the new version out and see whether your issue with the logs remain.

**Comment by crystall-bitquill** [comment]
Hi @truskare,

We've recently added an **experimental** Host Monitoring Plugin (PR #764) to the driver, called the Host Monitoring Plugin v2. More information can be found [here](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/using-plugins/UsingTheHostMonitoringPlugin.md#experimental-host-monitoring-plugin-v2). The Host Monitoring Plugin v2 is functionally equivalent to the Host Monitoring Plugin and they are configured using the same parameters. The Host Monitoring Plugin v2 was created to address the issues that you and others have been experiencing, and it is meant to be a more stable version of the Host Monitoring Plugin.

As it is currently an experimental plugin, please note that it should be tested before being used in a production environment. This plugin can be tried out by using the snapshot build [`aws-advanced-jdbc-wrapper-2.3.2-20231213.213138-10.jar`](https://aws.oss.sonatype.org/content/repositories/snapshots/software/amazon/jdbc/aws-advanced-jdbc-wrapper/2.3.2-SNAPSHOT/). For more information on using a snapshot build, see [this page](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/UsingTheJdbcDriver.md#using-a-snapshot-of-the-driver). If you are able to test out the plugin, please let us know if you encounter any errors or if this plugin was able to resolve the issues you've encountered.

Thank you!

**Comment by aaronchung-bitquill** [comment]
Hi @truskare ,

Heads up that the aforementioned experimental Host Monitoring Plugin is now available on our [latest release of the driver](https://search.maven.org/artifact/software.amazon.jdbc/aws-advanced-jdbc-wrapper/2.3.2/jar).

Also wanted to reiterate that it is currently an experimental plugin that should be tested before being used in a production environment.

If you are able to test out the plugin, please let us know if it resolves these issues or if there are any other issues encountered.

I'll be closing this ticket, but if this issue still persists or if you encounter any other issues, please feel free to create a new ticket or re-open this one.

Thank you
