### ISSUE TITLE
r2dbc support

### ISSUE THREAD

**Issue by gnagy** [awslabs/aws-advanced-jdbc-wrapper#774]
### Describe the feature

Do you have plans to implement support for reactive API / r2dbc?

### Use Case

We use r2dbc on our project

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### The AWS Advanced JDBC Driver version used

all

### JDK version used

any

### Operating System and version

any

**Comment by brunos-bq** [comment]
Hello @gnagy,

Thanks for reaching out with feedback.

Currently, we do not have any plans to support r2dbc.

If this changes in the future, we'll update this issue for visibility.
