### ISSUE TITLE
Use locks in favour of synchronized

### ISSUE THREAD

**Issue by davecramer** [awslabs/aws-advanced-jdbc-wrapper#783]
I think it would be better to use thread locks instead of synchronized.

https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/11bac60c308235333d645ea6e9c67ecf59bcfce3/wrapper/src/main/java/software/amazon/jdbc/authentication/AwsCredentialsManager.java#L25

**Comment by brunos-bq** [comment]
Fix was merged, closing issue.
