### ISSUE TITLE
Alternative option to RDS Library for IAM to avoid Lambda Size Limits.

### ISSUE THREAD

**Issue by rorychatterton** [awslabs/aws-advanced-jdbc-wrapper#788]
### Describe the feature

I would appreciate a smaller alternative to the RDS library to enable IAM Authentication, as the RDS library is extensive and provides many features that are not required for IAM RDS Auth to function.

### Use Case

The RDS dependency is an extensive library (22 MB uncompressed, 4 MB compressed), which causes issues when running on Lambda, which only allows for ~270 MB uncompressed across all layers.  

Having an alternative option that only provides the IAM Auth token flow should significantly reduce the required footprint when running on Lambda with JDBC. 

### Proposed Solution

I think the solution would be:
- An alternative library dependency option that only provides the necessary APIs to enable API Authentication or
- Integrating the IAM Token Fetch/Refresh workflow into the existing JDBC-wrapper

The dependencies on the rds library seem pretty light and can be found here:
https://github.com/search?q=repo%3Aawslabs%2Faws-advanced-jdbc-wrapper+software.amazon.awssdk.services.rds&type=code

### Other Information

Some context:
Considering the speedup that comes with Snapstart, we've been looking at using Native Java over Graalvm to increase our DevEx in the lower dev environments. This has meant that the size of the lambdas have significantly increased because we lose the benefit of GraalVM Tree shaking.

We're hitting the lambda limits using little more than Micronaut + Aurora Wrapper + Hibernate + Open Telemetry Collector + RDS. The **RDS library is the second largest jar in our manifest** behind Hibernate.

While Snapstart isn't "new" new, I suspect we'll see more issues like this as people experiment with it over Graal while using fuller frameworks like Micronaut/Spring/etc.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### The AWS Advanced JDBC Driver version used

2.2.5

### JDK version used

17.0.8

### Operating System and version

N/A

**Comment by sergiyvamz** [comment]
Hi @rorychatterton 

We've merged PR and the fix is now available in the latest [snapshot build](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/UsingTheJdbcDriver.md#using-a-snapshot-of-the-driver). We hope that the latest improvements help to solve your issue.

**Comment by rorychatterton** [comment]
Thankyou @sergiyvamz!

I'll test this in the next couple of days and let you know how I go.

**Comment by aaronchung-bitquill** [comment]
Hi @rorychatterton 

I know this ticket is closed, but I wanted to let you know that the fix is now available on the [latest version](https://central.sonatype.com/artifact/software.amazon.jdbc/aws-advanced-jdbc-wrapper/2.3.4) of the driver.

Thank you!
