### ISSUE TITLE
Relax overly-strict query type checking of "Results Producing" QueryReturnType, or provide override flag for batchUpdate()

### ISSUE THREAD

**Issue by benkanlu** [awslabs/aws-advanced-jdbc-wrapper#789]
### Describe the feature

Currently the QueryInfo.getQueryReturnType checks to see if the SQL may return any results. If it does and the underlying method called (specifically jdbcTemplate.batchUpdate(sql)) is called, it throws an error saying it is not allowed. 

"Caused by: org.springframework.dao.DataIntegrityViolationException: StatementCallback; SQL [
-- ]; Statement.executeUpdate() or Statement.executeLargeUpdate() cannot issue statements that produce result sets."

### Use Case

There are many use cases to use 'CALL/EXECUTE' or even other things like 'OPTIMIZE' or 'REPAIR' in an automated way by sending multiple statements through batchUpdate(), which reduces communication overhead. If it does return anything (like in an OPTIMIZE table for example), the results can just be ignored or discarded.

Previously, MySQL/MariaDB native drivers allowed this type of 'ignoring' results sets if a non-DML statement (i.e. DDL/DCL) was sent. 

### Proposed Solution

While tightening down the types of statements allowed in a batchUpdate() may work in many cases, an option/flag to override this functionality would help immensely with current code bases expecting such functionality. 

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### The AWS JDBC Driver for MySQL version used

Any version greater than 0.4.0 causes this issue.

### JDK version used

OpenJDK Runtime Environment Corretto-17.0.6.10.1 (build 17.0.6+10-LTS)

### Operating System and version

Windows 10 / Ubunutu 18.04

**Comment by benkanlu** [comment]
Any additional thoughts on my last comment/explanation above?

**Comment by crystall-bitquill** [comment]
Hi @benkanlu,

I recently opened a PR (#836) to add your suggestion, and it's been merged. The changes are available in the latest [snapshot build](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/UsingTheJdbcDriver.md#using-a-snapshot-of-the-driver), specifically [aws-advanced-jdbc-wrapper-2.3.3-20240120.032029-32.jar](https://aws.oss.sonatype.org/content/repositories/snapshots/software/amazon/jdbc/aws-advanced-jdbc-wrapper/2.3.3-SNAPSHOT/). Could you kindly check it out and let us know if this resolves the issue?

Thank you!

**Comment by benkanlu** [comment]
(Super late response) Yes, that now appears to work. using 'mariadb' in the url like 'jdbc:aws-wrapper:mariadb:/somecluster.us-east-1.rds.amazonaws.com:3306/yourdatabase' now correctly uses the 'aurora-mysql' dialect.

Thanks!
