### ISSUE TITLE
FailoverConnectionPlugin SessionStateTransferCallable capability

### ISSUE THREAD

**Issue by scott-long-adp** [awslabs/aws-advanced-jdbc-wrapper#812]
### Describe the bug

Converting this discussion into a ticket https://github.com/awslabs/aws-advanced-jdbc-wrapper/discussions/766

We are trying to validate the SessionStateTransferCallable configuration

It looks like SessionStateTransferCallable is called only by switchCurrentConnectionTo(), which requires a non-null value for this.pluginService.getCurrentConnection() in order to call transferSessionState() to copy properties from the old connection to the new.

But switchCurrentConnectionTo() is only actually called when this.pluginService.getCurrentConnection() is null.

This, I think, means switchCurrentConnectionTo() will never call transferSessionState() to copy properties from the old connection to the new.

As a result the failover just always goes through failoverReader() or failoverWriter(), which functionally does recover, but the switchCurrentConnectionTo() path is never taken, as far as I can tell --

Am I reading this correctly?

https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/wrapper/src/main/java/software/amazon/jdbc/plugin/failover/FailoverConnectionPlugin.java#L863

More specifically in FailoverConnectionPlugin.java:

- SessionStateTransferCallable() is invoked only by transferSessionState(), and only if this.pluginService.getCurrentConnection() is not null

- transferSessionState() is invoked only by switchCurrentConnectionTo()

- switchCurrentConnectionTo() is invoked only by connectTo()

- connectTo() is invoked only by pickNewConnection, and only if this.pluginService.getCurrentConnection() is null

I believe this means that SessionStateTransferCallable() can never be invoked, which seems to align with our tests so far where we do not observe it being called.  Unless there is another reason we are not observing SessionStateTransferCallable being invoked during failovers. 
 

### Expected Behavior

We were expecting SessionStateTransferCallable() to be invoked to copy connection properties during a failover. 

### What plugins are used? What other connection properties were set?

aws wrapper driver 2.3.1 , mysql connect driver 8.0.33

### Current Behavior

SessionStateTransferCallable is not invoked when an RDS failover is triggered during testing

### Reproduction Steps

Start an application pointing to an RDS database with both a reader and a writer, with aws wrapper driver 2.3.1 and mysql jdbc connect driver 8.0.33, then trigger a failover in the RDS mysql database, and observe that SessionStateTransferCallable is never invoked and that the driver fails over in the normal manner of letting the connection fall out of the pool and reconnect in the normal manner. 

### The AWS Advanced JDBC Driver version used

2.3.1

### JDK version used

jdk17

### Operating System and version

aws

**Comment by brunos-bq** [comment]
Hello @scott-long-adp,

As you can see in the issue timeline, we have recently merged a quick change to address the issue.

Could you kindly checkout our [snapshot](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/UsingTheJdbcDriver.md#using-a-snapshot-of-the-driver) build and let us know if the issue still persists?

Thank you!

**Comment by scott-long-adp** [comment]
Hi @brunos-bq -- thank you -- we will pull down a snapshot and get it into a test environment where we can fail over -- thanks again -- will report back --

**Comment by aaronchung-bitquill** [comment]
Hi @scott-long-adp 

Heads up that the fix is now available on the [latest version](https://search.maven.org/artifact/software.amazon.jdbc/aws-advanced-jdbc-wrapper/2.3.3/jar) of the AWS Advanced JDBC Driver.

Also, since there have not been updates on this ticket for some time, I'll be closing this ticket. However, if you require further assistance, you can reopen this issue, or create a new one.

Thank you!
