### ISSUE TITLE
Passing logServerErrorDetail=false seems to not take effect

### ISSUE THREAD

**Issue by abdoofathy95** [awslabs/aws-advanced-jdbc-wrapper#816]
### Describe the bug

I have passed logServerErrorDetail=false as part of the URL connecting to Aurora, but it seems SQL insertion errors still leak the data even tho the correct parameter is passed `logServerErrorDetail=false`, this works fine on postgres JDBC driver. 
https://jdbc.postgresql.org/documentation/use/#:~:text=logServerErrorDetail 

      `url: jdbc:aws-wrapper:postgresql://xxxx.eu-west-1.rds.amazonaws.com:5432/test_db?sslmode=verify-full&sslrootcert=/certs/global-bundle.pem&logServerErrorDetail=false`

### Expected Behavior

When logServerErrorDetail=false is passed, the SQL insertion errors should report only the SQL statement without the data being inserted.

Example: having the following SQL which inserts a malformed json into a jsonb column.

```java.sql.BatchUpdateException: INSERT INTO test_table(id, data) VALUES (?, (?)::jsonb)]; Batch entry 0 <unknown> was aborted: ERROR: invalid input syntax for type json```

### What plugins are used? What other connection properties were set?

auroraConnectionTracker,failover,iam

### Current Behavior

When running a malformed SQL the actual data being inserted is logged.

example:

java.sql.BatchUpdateException: Batch entry 0 INSERT INTO test_table(id, data) VALUES ('7555d945-9be6-4c2a-a3ac-0721ff2bd45d', ('{"id":"7555d945-9be6-4c2a-a3ac-0721ff2bd45d","version":1619607230162000000.0000000000,}{')::jsonb) was aborted: ERROR: invalid input syntax for type json
  Detail: Expected end of input, but found "{".

### Reproduction Steps

Just try to insert or update into a table and trigger a DataIntegrityException by inserting under the same primary key twice & include 
logServerErrorDetail=false 
in the parameters.

### The AWS Advanced JDBC Driver version used

2.2.4

### JDK version used

oracle-jdk:17 (17.0.6+9-LTS-190)

### Operating System and version

Red Hat Enterprise Linux 8.7 (Ootpa)

**Comment by brunos-bq** [comment]
Hi @abdoofathy95,

Thanks for reaching out and raising this issue.

We'll take a look at this and keep you updated as we investigate.

Thank you for your patience!

**Comment by crystall-bitquill** [comment]
Hi @abdoofathy95,

I tried to reproduce this issue by doing a batch execute to insert entries using the same primary key but the `logServerErrorDetail` parameter seemed to be working as expected. The test code looked like this:
```java
private static final String connString = "jdbc:aws-wrapper:postgresql://database-pg-name.cluster-XYZ.us-east-2.rds.amazonaws.com:5432/connectionSample?logServerErrorDetail=false";
final Properties properties = new Properties();
properties.setProperty("user", "myUser");
properties.setProperty("wrapperPlugins", "auroraConnectionTracker,failover,iam");
properties.setProperty("wrapperLoggerLevel", "all");

try (Connection conn = DriverManager.getConnection(connString, properties)) {
  PreparedStatement statement = conn.prepareStatement("INSERT INTO myTable(test) VALUES(1)");
  statement.addBatch();
  statement.addBatch();
  statement.executeBatch();
} catch (SQLException e) {
  System.out.println(e.getMessage());
}
```

When the exception was caught, this is what the message contained when `logServerErrorDetail` was set to `false`:
```
Batch entry 0 <unknown> was aborted: ERROR: duplicate key value violates unique constraint "myTable_pkey"  Call getNextException to see other errors in the batch.
```

This seems consistent with how the PostgreSQL JDBC Driver behaves. Is there anything in this setup that you think might be missing or significantly different?

To figure out what the issue might be, I have a few questions for you:
- Do you have a logger properties file set up? If so, how is it configured?
- Are you able to provide logs? If not, can you confirm if it was a message from the AWS JDBC Driver logs, or from the PostgreSQL JDBC Driver logs?

Thank you!

**Comment by abdoofathy95** [comment]
Hey, thank you for your response, I will try to test this again and remove any "noise" 

I have no logger properties file set up.
The logs are coming from PostgreSQL JDBC driver.
