### ISSUE TITLE
efm2 startMonitoring ConcurrentModificationException

### ISSUE THREAD

**Issue by ibaiul** [awslabs/aws-advanced-jdbc-wrapper#893]
### Describe the bug

The `efm2` plugin is throwing `ConcurrentModificationException` when executing database queries. The exception occurs in a low percentage of requests but enough to be noticed.

### Expected Behavior

The plugin should be able to monitor connections concurrently without failure.

The`efm` v1 plugin does not suffer from this behaviour.

### What plugins are used? What other connection properties were set?

failover,efm2

### Current Behavior

**Exception**
```
caused by java.util.ConcurrentModificationException:
  java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1221)
  software.amazon.jdbc.plugin.efm2.MonitorImpl.startMonitoring(MonitorImpl.java:169)
  software.amazon.jdbc.plugin.efm2.MonitorServiceImpl.startMonitoring(MonitorServiceImpl.java:118)
  software.amazon.jdbc.plugin.efm2.HostMonitoringConnectionPlugin.execute(HostMonitoringConnectionPlugin.java:169)
  software.amazon.jdbc.ConnectionPluginManager.lambda$execute$5(ConnectionPluginManager.java:323)
  software.amazon.jdbc.ConnectionPluginManager.lambda$null$3(ConnectionPluginManager.java:260)
  software.amazon.jdbc.ConnectionPluginManager.executeWithTelemetry(ConnectionPluginManager.java:233)
  software.amazon.jdbc.ConnectionPluginManager.lambda$makePluginChainFunc$4(ConnectionPluginManager.java:260)
  software.amazon.jdbc.ConnectionPluginManager.lambda$null$2(ConnectionPluginManager.java:261)
  software.amazon.jdbc.plugin.failover.FailoverConnectionPlugin.execute(FailoverConnectionPlugin.java:225)
  software.amazon.jdbc.ConnectionPluginManager.lambda$execute$5(ConnectionPluginManager.java:323)
  software.amazon.jdbc.ConnectionPluginManager.lambda$null$3(ConnectionPluginManager.java:260)
  software.amazon.jdbc.ConnectionPluginManager.executeWithTelemetry(ConnectionPluginManager.java:233)
  software.amazon.jdbc.ConnectionPluginManager.lambda$makePluginChainFunc$4(ConnectionPluginManager.java:260)
  software.amazon.jdbc.ConnectionPluginManager.executeWithSubscribedPlugins(ConnectionPluginManager.java:223)
  software.amazon.jdbc.ConnectionPluginManager.execute(ConnectionPluginManager.java:320)
  software.amazon.jdbc.util.WrapperUtils.executeWithPlugins(WrapperUtils.java:237)
  software.amazon.jdbc.wrapper.PreparedStatementWrapper.execute(PreparedStatementWrapper.java:140)
  com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
  com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
  org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:209)
  org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:3626)
  org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:268)
  org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:350)
  org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:393)
  org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:380)
  org.jooq.impl.AbstractResultQuery.fetchOne(AbstractResultQuery.java:545)
  org.jooq.impl.AbstractResultQuery.fetchOne(AbstractResultQuery.java:481)
  org.jooq.impl.SelectImpl.fetchOne(SelectImpl.java:2819)
```

**Log**
```
HikariPool-1 - Failed to validate connection software.amazon.jdbc.wrapper.ConnectionWrapper@26aa402d - com.mysql.cj.jdbc.ConnectionImpl@7343871c (java.util.ConcurrentModificationException). Possibly consider using a shorter maxLifetime value
```

### Reproduction Steps

Execute queries in a environment with many read/writes per minute

This is an example query that throws the exception, although the query itself should not be relevant to reproduce the issue.

It is executed using the `DSLContext` provided by `jOOQ` which has been initialized providing a `HikariDatasource`

```
dsl.select(FOO.BAR)
    .from(FOO)
    .where(FOO.BAR.eq(1))
    .fetchOne(FOO.BAR)
```

### Possible Solution

Possible solution may be to use a concurrent structure such as a `ConcurrentHashMap` to store the [`newContexts`](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/38122696e40cbfa15fbe2383a4d3af0d05408417/wrapper/src/main/java/software/amazon/jdbc/plugin/efm2/MonitorImpl.java#L61C17-L61C24).

In v1 of `efm` plugin a [concurrent structure](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/38122696e40cbfa15fbe2383a4d3af0d05408417/wrapper/src/main/java/software/amazon/jdbc/plugin/efm/MonitorImpl.java#L62C49-L62C60) is being used.

### Additional Information/Context

Application instance executes ~ 2500 reads + 2500 writes per minute using `jOOQ`

### The AWS Advanced JDBC Driver version used

2.3.3

### JDK version used

openjdk version "17.0.10" 2024-01-16 LTS OpenJDK Runtime Environment Corretto-17.0.10.8.1 (build 17.0.10+8-LTS) OpenJDK 64-Bit Server VM Corretto-17.0.10.8.1 (build 17.0.10+8-LTS, mixed mode, sharing)

### Operating System and version

Ubuntu 22.04 LTS

**Comment by jasonli-improving** [comment]
Hi @ibaiul,

Similar issues have been reported (https://github.com/awslabs/aws-advanced-jdbc-wrapper/issues/855) regarding this error.

We have merged in a fix for this (PR https://github.com/awslabs/aws-advanced-jdbc-wrapper/pull/876). Could you kindly checkout our [snapshot](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/UsingTheJdbcDriver.md#using-a-snapshot-of-the-driver) build and let us know if the issue still persists?

Thank you!

**Comment by ibaiul** [comment]
Hi @jasonli-improving 

Today we tested the `2.3.4-SNAPSHOT` version under the same conditions and it worked without throwing any errors.

As far as we are concerned this issue is fixed.

**Comment by jasonli-improving** [comment]
Hi @ryanemerson,

We are planning on having a release for version 2.3.4 by the end of this week.

**Comment by aaronchung-bitquill** [comment]
Hi @ibaiul @ryanemerson 

The fix is now available on the [latest version](https://central.sonatype.com/artifact/software.amazon.jdbc/aws-advanced-jdbc-wrapper/2.3.4) of the driver.

I'll be closing this ticket now. But if you require further assistance,  feel free to reopen this issue, or create a new one.

Thank you!
