### ISSUE TITLE
Perfomance degradation with "auroraConnectionTracker,failover,efm2" and version 2.3.4

### ISSUE THREAD

**Issue by orenshafir** [awslabs/aws-advanced-jdbc-wrapper#921]
### Describe the bug

Using version `2.3.4` with `"auroraConnectionTracker,failover,efm2"`, we have noticed a performance degradation. When enabled, we noticed a 94.85% decrease in performance.

### Expected Behavior

We would expect no performance degradation. 

### What plugins are used? What other connection properties were set?

"auroraConnectionTracker,failover,efm2"

### Current Behavior

I ran a stress test on our service, once using our current main branch's code, once using version 2.3.3 with "auroraConnectionTracker,failover,efm2", and once using version 2.3.4 with "auroraConnectionTracker,failover,efm2". 

Over the course of 12 minutes here were the results:

1. On main (no aws-advanced-jdbc-wrapper) we saw 10974 total requests and around 15.2335 req/s
2. With version 2.3.3 and "auroraConnectionTracker,failover,efm2" plugins we saw 11041 total requests and around 15.310103 req/s. We did however encounter the [ConcurrentModificationException](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/bec3ba140eff04eba639db2563933dee3c755e1c/CHANGELOG.md#bug-fixed) issue that was fixed by version 2.3.4
3. With version 2.3.4 and "auroraConnectionTracker,failover,efm2" plugins we saw 1776 total requests and around 2.464188 req/s. We also experienced a connection leak.

### Reproduction Steps

1. Using version `2.3.4` of the [aws-advanced-jdbc-wrapper](https://github.com/awslabs/aws-advanced-jdbc-wrapper/tree/bec3ba140eff04eba639db2563933dee3c755e1c), and the `"auroraConnectionTracker,failover,efm2"` plugins, run a stress test
2. Using version `2.3.3` of the [aws-advanced-jdbc-wrapper](https://github.com/awslabs/aws-advanced-jdbc-wrapper/tree/bec3ba140eff04eba639db2563933dee3c755e1c), and the `"auroraConnectionTracker,failover,efm2"` plugins, run a stress test

### Additional Information/Context

It looks like [benchmarks](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/development-guide/DevelopmentGuide.md#aws-jdbc-driver-benchmarks) indicate that there was degraded performance when using the efm2 plugin.

### The AWS Advanced JDBC Driver version used

2.3.4 and 2.3.3

### JDK version used

openjdk version "11.0.17"

### Operating System and version

MacOS Sonoma 14.2.1

**Comment by er1c** [comment]
@ahus1 

> I see the code has changed to fix https://github.com/awslabs/aws-advanced-jdbc-wrapper/issues/917, still there seems to be a global lock still exists afterwards, and I fear that the problem will persist.

That fix for #917 isn't released yet, just curious if you tried with a locally built against master, or if that will possibly solve this issue.

**Comment by aaronchung-bitquill** [comment]
Hello all,

Thanks for reaching out and raising this issue. 

We'll take a look at this as well and keep you guys updated as we investigate. 

Also, fix https://github.com/awslabs/aws-advanced-jdbc-wrapper/issues/917 is available on our latest [snapshot](https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/UsingTheJdbcDriver.md#using-a-snapshot-of-the-driver) build. 
Could you check it out and let us know if the issue still persists? 

Thank you!

**Comment by ahus1** [comment]
I have tested version `aws-advanced-jdbc-wrapper-2.3.5-20240311.214042-12.jar` and it didn't show that issue any more.

**Comment by orenshafir** [comment]
@aaronchung-bitquill I also tested the latest snapshot `2.3.5-SNAPSHOT` an everything seems to be working. Any idea when the version will actually be officially deployed/released?

**Comment by eloo-abi** [comment]
Hi, 
we have right now tested 2.3.5 and see a big improvement to 2.3.4 but still the performance compared to 2.3.3 has degraded.

![image](https://github.com/awslabs/aws-advanced-jdbc-wrapper/assets/49561925/86c28a77-b7d2-4fe0-b459-dbb13b577184)

The marks are showing the version 2.3.3, 2.3.4 and 2.3.5

**Comment by orenshafir** [comment]
@aaronchung-bitquill a question related to what @eloo-abi just posted, is 2.3.3 stable enough to use for now?

**Comment by aaronchung-bitquill** [comment]
Hi all,

[Release 2.3.5](https://search.maven.org/artifact/software.amazon.jdbc/aws-advanced-jdbc-wrapper/2.3.5/jar?eh=)  is officially now available. 

Can you check it out let us know if the issue still persists? 

Thank you

**Comment by er1c** [comment]
Can confirm 2.3.3 > 2.3.5 > 2.3.4 when using in our stage env.

**Comment by aaronchung-bitquill** [comment]
@eloo-abi @er1c  I was wondering if you could share more details about the following? 

- what plugins are you using?
- are you using any particular frameworks in conjunctions with the driver? (ex. Hibernate)
- what type of queries are you executing? 
- what tooling are you using to observe performance? 

Thank you!

**Comment by er1c** [comment]
@aaronchung-bitquill 

base line is 100% - no jdbc wrapper (queries/sec) - all reads over ~~ 15 minutes using k6 to request the same endpoint, using scala play/slick with a HikariCP w/ default jdbc plugins
- 2.3.3 - 102% (this actually brings in a newer PG DataSource than our main)
- 2.3.4 - 18%
- 2.3.5 - 97%

So I guess the diff could just be in the realm of marginal error between 2.3.3 and 2.3.5.

**Comment by eloo-abi** [comment]
@aaronchung-bitquill 

We are using: the following options: `wrapperDialect=aurora-mysql&wrapperPlugins=auroraConnectionTracker,failover,efm`
Frameworks: Hibernate, HikariCP and MariaDB JDBC Driver
TestTool: K6 with 50 rps
Monitoring: Micrometer included in our SpringBoot App
Queries: Just simple SELECTs

and as @er1c mentioned i also suggest this is only related to the changed between 2.3.3 and 2.3.5.
I have tested the same code base with 2.3.3, 2.3.4 and 2.3.5 as mentioned above.

**Comment by aaronchung-bitquill** [comment]
Hi all,

I'm still currently investigating this, but I thought I should share some of my findings as well. 

So I did three separate tests at different times to try to eliminate the variance of network latency.
Initially, I ran the tests at 250 users first using versions 2.3.3, then 2.3.5. Then at a later time, I did a test at 500 users first using  version 2.3.3, then 2.3.5. Then at another time, did another test round at 500 users. 

Setup
- Driver Plugins: failover,efm2
- Frameworks/Libraries: Spring Boot, HikariCP, PostgreSQL JDBC Driver
- Test Tool: Locust
- Queries: Simple selects

Results
2.3.3 - 250 Users
- RPS: 155.9
- Average Response Time: 79ms
- 99% Response Time: 110ms

2.3.5 - 250 Users
- RPS: 155.3
- Average Response Time: 78ms
- 99% Response Time: 110ms

2.3.3 - 500 Users - First run
- RPS: 261.1
- Average Response Time: 351ms
- 99% Response Time: 770ms

2.3.5 - 500 Users - First run
- RPS: 257.5
- Average Response Time: 367ms
- 99% Response Time: 790ms

2.3.3 - 500 Users - Second run
- RPS: 259.5
- Average Response Time: 350ms
- 99% Response Time: 800ms

2.3.5 - 500 Users - Second run
- RPS:  260
- Average Response Time: 352ms
- 99% Response Time: 800ms

So it doesn't look like there is much of a difference versions `2.3.3` and `2.3.5`. Only case it was noticeably difference was in the 500 Users First run case. The average response times from 2.3.3 to 2.3.5 rose from 351ms to 367ms. That is an increase of 4.5%. As @er1c mentioned, the difference could be within the margin of error. Also, the 2 other cases had even smaller differences. Nonetheless, this is still preliminary and I will continue to investigate. 

@eloo-abi This is a bit late of me to ask, but I am having a bit of trouble interpreting the graphs you provided. Would you explain or summarize them for me? 

Thank you

**Comment by er1c** [comment]
We've been stable in production with `2.3.5`

**Comment by aaronchung-bitquill** [comment]
Thanks everyone for your input on this one. 

I will now be closing this issue. 

However, if anyone requires further assistance, you can reopen this issue, or create a new one.

Thank you!
